source/structure_formation.power_spectrum.variance.window_function.ETHOS.F90, source/structure_formation.transfer_function.ETHOS.F90, source/structure_formation.transfer_function.Hu2008fuzzy.F90, source/structure_formation.transfer_function.Murgia2017.F90, source/structure_formation.transfer_function.fuzzyDM.F90
Added some comments to my transfer and window functions so they actually explain what they are.
=> Comments added to David's changes

source/dark_matter_profiles.heating.tidal.F90, source/dark_matter_profiles_DMO.heated.F90
* Set the 2nd order tidal heating term to zero by default, for consistency with the original model.
* If the 2nd order tidal heating term coefficient is zero, do not evaluate the term (optimization).
=> Restore (by default) the original tidal heating model behavior

source/nodes.property_extractor.SED.F90
This is intended to be useful for seeing which files are utilized and for debugging purposes.
=> Add messages reporting on file write/read for the "SED" nodePropertyExtractor

source/nodes.property_extractor.SED.F90, source/nodes.property_extractor.luminosity_stellar_from_SED.F90
Adds a new nodePropertyExtractor which computes the stellar luminosity under a filter response curve from a stellar SED.
=> Add a "stellar luminosity from SED" property extractor

source/tasks.halo_mass_function.F90
Allows for a user-supplied list of virial density contrast definitions. Halo masses (and radii) are output for each such definition.
=> Support output of halo masses under arbitrary definitions from the halo mass function task

source/accretion.halo.cold_mode.F90, source/cooling.cooling_function.CIE_file.F90, source/cooling.cooling_function.CMB_Compton.F90, source/cooling.cooling_function.F90, source/cooling.cooling_function.atomic_CIE_Cloudy.F90, source/cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90, source/cooling.cooling_function.summation.F90, source/cooling.cooling_function.velocity_cut_off.F90, source/cooling.cooling_radius.beta_profile.F90, source/cooling.cooling_radius.isothermal_profile.F90, source/cooling.cooling_radius.simple.F90, source/cooling.cooling_time.F90, source/cooling.cooling_time.simple.F90, source/cooling.time_available.Benson_Bower_2010.F90, source/merger_trees.operators.monotonize_mass_growth.F90, source/merger_trees.operators.prune_branch_complement.F90, source/nodes.operators.physics.cooling_energy_radiated.F90, source/nodes.property_extractor.ICM_Xray_luminosity.F90, source/nodes.property_extractor.ICM_cooling_power_in_band.F90, source/objects.nodes.components.hot_halo.standard.F90
Adds the [Benson & Bower (2010)](https://ui.adsabs.harvard.edu/abs/2010MNRAS.405.1573B/abstract) model for the time available for cooling based on an estimate of the energy radiated by the CGM over the history of the halo.
Includes some auxiliary patches which prepare for this by allow the coolingFunction class to access all node properties.
=> Add implementation of the cooling model of Benson & Bower (2010)

source/nBody.import.GadgetHDF5.F90, source/nBody.operator.mean_position.F90, source/nBody.operator.self_bound.F90
Adds an N-body operator to compute kinetic and potential energy tensors. Also, stores results of N-body operators into the simulation property hash.
=> Adds an N-body operator to compute kinetic and potential energy tensors

source/nBody.operator.angular_momentum.F90, source/nBody.operator.energy_tensors.F90
Also rotates the coordinate system into alignment with the principal axes of the energy tensor.
=> Measure energy tensors in zero linear and angular momentum frame

source/merger_trees.operators.particulate.F90, testSuite/parameters/particulateTree.xml, testSuite/regressions/particulate.xml
Also includes a test suite entry to run a simple particulate model.
=> Add option to control tolerance of smoothing integrals in the "particulate" merger tree operator

perl/Galacticus/Build/Components/TreeNodes/Serialization.pm, scripts/analysis/metaAnalysis.pl, source/galactic_structure.radius_solver.fixed.F90, source/merger_trees.evolve.profiler.F90, source/merger_trees.evolve.profiler.null.F90, source/merger_trees.evolve.profiler.simple.F90, source/merger_trees.node_evolver.standard.F90
Now collects data on:
* number of ODE evaluations for each successful step;
* CPU time used for each succesful step;
* whether the step was interrupted.
=> Extend the data collected by the tree evolve profiler class 

source/dark_matter_profiles.SIDM.isothermal.F90, source/dark_matter_profiles.adiabatic_Gnedin2004.F90, source/dark_matter_profiles.generic.F90, source/dark_matter_profiles.heating.null.F90, source/dark_matter_profiles.heating.summation.F90, source/dark_matter_profiles.heating.tidal.F90, source/dark_matter_profiles.heating.two_body_relaxation.F90, source/dark_matter_profiles_DMO.F90, source/dark_matter_profiles_DMO.Penarrubia2010.F90, source/dark_matter_profiles_DMO.SIDM.coreNFW.F90, source/dark_matter_profiles_DMO.SIDM.isothermal.F90, source/dark_matter_profiles_DMO.Zhao1996.F90, source/dark_matter_profiles_DMO.finite_resolution.F90, source/dark_matter_profiles_DMO.heated.F90, source/dark_matter_profiles_DMO.heated.monotonic.F90, source/dark_matter_profiles_DMO.truncated.F90, source/dark_matter_profiles_DMO.truncated.exponential.F90, source/satellites.tidal_heating.rate.Gnedin1999.F90, source/satellites.tidal_stripping.radius.King1962.F90, source/satellites.tidal_stripping.rate.Zentner2005.F90, source/tests.dark_matter_halo_radius_enclosing_mass.F90, source/tests.dark_matter_profiles.heated.F90, testSuite/parameters/tidalTracksMonotonic_gamma0.0.xml, testSuite/parameters/tidalTracksMonotonic_gamma0.5.xml, testSuite/parameters/tidalTracksMonotonic_gamma1.0.xml, testSuite/parameters/tidalTracksNonMonotonic_gamma1.0.xml, testSuite/test-tidalTracks.pl
Also includes several optimizations of density profile calculations.
=> Adds an improved tidal heating model which works for cored density profiles

source/geometry.lightcones.square.F90, source/merger_trees.construct.read.F90, source/merger_trees.evolve.timesteps.satellite.F90, source/merger_trees.operators.assign_orbits.F90, source/nodes.operators.physics.satellite_merging.radius_trigger.F90, source/objects.nodes.components.disk.very_simple.F90, source/objects.nodes.components.satellite.orbiting.F90, source/objects.nodes.components.satellite.orbiting.bound_functions.Inc, source/objects.nodes.components.satellite.preset.F90, source/objects.nodes.components.satellite.preset.bound_functions.Inc, source/objects.nodes.components.satellite.standard.F90, source/objects.nodes.components.satellite.standard.bound_functions.Inc, source/objects.nodes.components.satellite.very_simple.F90, source/objects.nodes.components.satellite.very_simple.bound_functions.Inc, source/satellites.merging.timescale.preset.F90
In satellite components "mergeTime" is now "timeUntilMerging".
=> Change property name to be more descriptive

source/dark_matter_profiles_DMO.truncated.exponential.F90, source/nBody.operator.filter_ID.F90, source/nBody.operator.inertia_tensor.F90, source/nBody.operator.self_bound.F90
Also finds the eigenvectors, eigenvalues, and axis ratios.
=> Add an N-body operator which computes the inertia tensor

source/structure_formation.transfer_function.BBKS.F90, source/structure_formation.transfer_function.BBKS.WDM.F90, source/structure_formation.transfer_function.Bode2001.F90, source/structure_formation.transfer_function.ETHOS.F90, source/structure_formation.transfer_function.Eisenstein_Hu.F90, source/structure_formation.transfer_function.F90, source/structure_formation.transfer_function.Hu2000.FDM.F90, source/structure_formation.transfer_function.Murgia2017.F90, source/structure_formation.transfer_function.accelerator.F90, source/structure_formation.transfer_function.envelope.F90, source/structure_formation.transfer_function.file.F90, source/structure_formation.transfer_function.identity.F90, source/tasks.halo_mass_function.F90, source/tests.excursion_sets.F90, source/tests.merger_tree_branching.F90, source/tests.power_spectrum.F90, source/tests.sigma.F90, source/tests.spherical_collapse.baryons_dark_matter.F90
These are output at the half-, quarter-, and other-mode masses.
=> In the `taskHaloMassFunction` class output logarithmic slopes of the transfer function

source/accretion_disks.spectra.Hopkins2007.F90, source/geometry.surveys.Bernardi-2013-SDSS.F90, source/geometry.surveys.Li-White-2009-SDSS.F90, source/merger_trees.node_evolver.standard.F90, source/structure_formation.power_spectrum.nonlinear.CosmicEmu.F90, source/tests.DiemerKravtsov2014_concentration.F90, testSuite/test-merger-tree-builder.pl, testSuite/test-reproducibility.pl
Improves portability (to systems which do not have `wget` installed).
=> Replace use of `wget` with `download()` function

doc/Galacticus.bib, source/accretion.halo.F90, source/accretion.halo.Naoz_Barkana_2007.F90, source/accretion.halo.cold_mode.F90, source/accretion.halo.simple.F90, source/accretion.halo.zero.F90, source/intergalactic_medium.state.F90, source/intergalactic_medium.state.metallicity.AstraeusV.F90, source/intergalactic_medium.state.metallicity.fixed.F90, source/objects.nodes.components.hot_halo.standard.F90
Adds support for a non-zero metallicity in the IGM, and accretion of this onto halos.
=> IGM metallicity support

source/dark_matter_profiles.heating.summation.F90, source/star_formation.rate_surface_density.disks.Blitz2006.F90, testSuite/benchmark-darkMatterOnlySubhalos.pl, testSuite/benchmark-milkyWay.pl, testSuite/validate-darkMatterOnlySubhalos.pl, testSuite/validate-milkyWay.pl
Uses analytic, approximate, and tabulated solutions.
=> Optimizations of Blitz2000 star formation rate class

Makefile, scripts/build/codeDirectivesParse.pl, scripts/build/libraryInterfacesDependencies.pl, scripts/build/moduleDependencies.pl, source/cosmology.functions.F90
Ensure that sub-modules are rebuilt as needed by changing order-only dependencies in the `Makefile` to actual dependencies.
=> Fix build dependencies

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm, source/cooling.cooling_function.summation.F90, source/dark_matter_profiles.heating.summation.F90, source/galactic.filters.all.F90, source/galactic.filters.any.F90, source/geometry.surveys.combined.F90, source/merger_trees.evolve.timesteps.multi.F90, source/merger_trees.filter.all.F90, source/merger_trees.filter.any.F90, source/merger_trees.operators.sequence.F90, source/merger_trees.outputter.multi.F90, source/nBody.import.merge.F90, source/nBody.import.multiple.F90, source/nBody.operator.sequence.F90, source/nodes.operators.multi.F90, source/nodes.property_extractor.multi.F90, source/output.analyses.distribution_normalizer.sequence.F90, source/output.analyses.distribution_operator.sequence.F90, source/output.analyses.multi.F90, source/output.analyses.property_operator.sequence.F90, source/output.analyses.weight_operator.sequence.F90, source/radiation.summation.F90, source/radiative_transfer.outputter.multi.F90, source/radiative_transfer.source.summation.F90, source/stellar_feedback.outflows.summation.F90, source/stellar_populations.spectra.postprocess.sequence.F90, source/tasks.multi.F90
Also unifies the linked list descriptors used for state store/restore, deep copy, and allowed parameter functions.
=> Implement auto-descriptors for `functionClass` objects that use linked lists

.github/workflows/benchmarks.yml, .github/workflows/profiling.yml, .github/workflows/testRegressions.yml, .github/workflows/validate.yml
This is a trial to see if caching is useful.
=> Use caching in GitHub Actions for the benchmark workflow

source/utility.input_parameters.F90
This can be useful when checking for a `functionClass` object to be constructed by an `objectBuilder` directive that will search for the object through parent parameters if necessary.
=> Allow the `isPresent()` function of the `inputParameters` class to (optionally) search through parent parameters also

source/utility.IO.XML.F90
This is achieved by re-writing relative paths on-the-fly such that they are always relative to the original parameter file.
=> Allow multiple levels of `xi:include` in parameter files

testSuite/parameters/benchmark_milkyWay.xml, testSuite/parameters/validate_milkyWay.xml
In response to speed improvements.
=> Boost resolution of Milky Way model

source/accretion.halo.Naoz_Barkana_2007.F90, source/accretion.halo.cold_mode.F90, source/cosmology.parameters.simple.F90, source/dark_matter_halos.spins.distributions.delta_function.F90, source/galactic.filters.ISM_mass.F90, source/galactic.filters.basic_mass.F90, source/galactic.filters.stellar_mass.F90, source/galactic.filters.stellar_mass_morphology.F90, source/merger_trees.construct.build.mass_resolution.fixed.F90, source/merger_trees.construct.build.masses.sampled_distribution.F90, source/merger_trees.construct.read.importer.SussingMergerTrees.ASCII.F90, source/merger_trees.operators.dump_to_GraphViz.F90, source/merger_trees.operators.information_content.F90, source/merger_trees.operators.prune_by_mass.F90, source/merger_trees.operators.prune_non_essential.F90, source/merger_trees.operators.select_within_range.F90, source/stellar_feedback.outflows.power_law.redshift_scaling.F90, source/structure_formation.excursion_sets.barrier.remap.Sheth-Mo-Tormen.F90, source/structure_formation.excursion_sets.barrier.remap.scale.F90, source/structure_formation.unevolved_subhalo_mass_function.Giocoli2008.F90
This cleans up the handful of cases where this was not done already.
=> Unify constructors by calling the internal constructor where possible

parameters/reference/evolutionGalaxyFormation.xml, source/radiation.intergalactic_background.file.F90
This is much faster to read than XML for large datasets.
=> Support HDF5 format for intergalactic background radiation data files

source/nodes.operators.physics.CGM.chemistry.F90
=> Trap zero hot halo outer radius

source/hot_halo.ram_pressure_stripping.Font2008.F90
Previously upper and lower limits on the root interval were tested and, if a root existed in the interval, these were passed to the root-finding function. But, due to retabulations and the associated rounding errors it was possible on rare occasions for the root to move slightly outside of the interval between testing and calling the root finder. To avoid this we now add some buffer to the interval passed to the root finder.
=> fix: Avoid root search range failure in `font2008` hot halo ram pressure stripping class

perl/Galacticus/Build/SourceTree/Process/ClassDocumentation.pm, perl/Galacticus/Build/SourceTree/Process/StateStorable.pm, source/accretion.halo.Naoz_Barkana_2007.F90, source/numerical.interpolation.F90, source/objects.coordinates.F90, source/tests.interpolation.F90
Currently supports only linear interpolation and no extrapolation.
=> Add a simple 2D interpolator class

source/cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90, source/nodes.operators.physics.CGM.chemistry.F90
Simply skip evaluation for unphysically small densities.
=> Avoid floating point errors in molecular hydrogen chemistry

parameters/reference/evolutionDarkMatterOnly.xml, parameters/reference/evolutionGalaxyFormation.xml, parameters/tutorials/darkMatterOnlySubHalos.xml, source/nodes.operators.physics.satellite_destruction.mass_threshold.F90, testSuite/parameters/impulsiveHeating.xml, testSuite/parameters/satelliteDistanceMinimum.xml, testSuite/parameters/tidalTracksMonotonic_gamma0.0.xml, testSuite/parameters/tidalTracksMonotonic_gamma0.5.xml, testSuite/parameters/tidalTracksMonotonic_gamma1.0.xml, testSuite/parameters/tidalTracksNonMonotonic_gamma1.0.xml, testSuite/regressions/issue142.xml, testSuite/regressions/particulate.xml, testSuite/test-methods.xml
BREAKING CHANGE: Changes the names of parameters controlling the destruction thresholds.
=> Allow satellite destruction mass threshold to additionally scale with the tree mass

perl/Galacticus/Build/Components/TreeNodes/Serialization.pm, perl/Galacticus/Build/FunctionGlobal.pm, scripts/build/buildCode.pl, source/hot_halo.ram_pressure_stripping.Font2008.F90, source/merger_trees.construct.state_restore.F90, source/models.likelihoods.gaussian_regression.F90, source/state.F90
This helps to avoid root-bracketing failures which occur in systems that are physically highly-implausible.
=> In `hotHaloRamPressureStrippingFont2008` only solve ram pressure stripping for physically-plausible systems

.github/workflows/cicd.yml, scripts/build/buildProfiler.pl
Results are added to the `gh-pages` branch and published.
=> Add build profiling to the CI/CD workflow

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
Previously this worked with a simple approach of appending parameter names to a list, with no checking if those names were already on the list. This involves extending the list to allow new entries to be added, which in turn involves (potentially many) cycles of array creation, copying, and destruction. For large classes (e.g. ones that composite hundreds to thousands of other classes) this can be slow as it scales as $O(N^2)$. This new approach only adds new entries if they are not already on the list. So, it has higher overhead for short lists (but that is not really a problem), but avoids the list becoming huge which resulted in the poor scaling.
=> Improve run-time scaling of `allowedParameters()` methods for very large classes

source/interface.AxionCAMB.F90, testSuite/test-transfer-functions-axion.pl
[AxionCAMB](https://github.com/dgrin1/axionCAMB) received an [update](https://github.com/dgrin1/axionCAMB#bug-fix-4262023) which required some minor adjustments to how we patch the `Makefile` to allow Galacticus to build it, and some minor tolerance changes to the axion transfer function test case.
=> Updates in response to updated to AxionCAMB

.github/workflows/cicd.yml, doc/Galacticus.bib, perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm, source/merger_trees.evolve.timesteps.star_formation_history.F90, source/nodes.property_extractor.SED.F90, source/stellar_populations.spectra.postprocess.birth_clouds.Lacey2016.F90
Allows for postprocessing of spectral templates used in SED construction.
Also adds a timestepper class which ensures that all bins of the star formation history are populated.
=> Improve SED calculation

source/nodes.property_extractor.lightcone.F90
In the `nodePropertyExtractorLightcone` class add an option to make nodes falling outside of the lightcone non-fatal. Such nodes are simply assigned unphysical values for lightcone properties.
=> Add option to prevent fatal error for nodes outside of the lightcone

source/merger_trees.construct.read.F90
This is necessary to ensure, for example, that scale radii are set where needed.
=> Ensure that `nodeOperator` `treeInitialize` methods are applied to all nodes built from a merger tree file

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm, perl/Galacticus/Build/SourceTree/Process/MetaPropertyDatabase.pm
This PR specifically reduces duplication in the `deepCopy` code. Future PRs on this branch will address duplication elsewhere.
=> Avoid code duplication in source code preprocessor

source/nodes.property_extractor.projected_density.F90
Also fixes a bug which prevented some mass from being counted.
=> Include mass outside of the virial radius in projected density calculations

.github/workflows/cicd.yml, source/nodes.property_extractor.projected_mass.F90, source/nodes.property_extractor.tidally_truncated_NFW_fit.F90, source/tests.dark_matter_profiles.projected.F90, testSuite/parameters/darkMatterProfilesProjected.xml, testSuite/parameters/tidallyTruncatedNFWFit.xml, testSuite/test-tidallyTruncatedNFWFit.pl
Also fixes bugs in the projected density calculation, provides a tidally truncated NFW profile fitter, and provides test case code for projected masses and densities.
=> Implement projected mass profile calculations

source/nodes.property_extractor.tidally_truncated_NFW_fit.F90
- Added an additional output property that extracts the normalization of the density profile from the TNFW fit.
=> TNFW fit extractor aditional properties

source/geometry.surveys.Bernardi-2013-SDSS.F90, source/geometry.surveys.Li-White-2009-SDSS.F90, source/interface.CAMB.F90, source/interface.CLASS.F90, source/interface.Cloudy.F90, source/interface.FSPS.F90, source/interface.RecFast.F90, source/structure_formation.power_spectrum.nonlinear.CosmicEmu.F90, source/system.downloader.F90
Activate this for RecFast downloads which often fail.
=> Allow retries of failed downloads

source/cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90, source/star_formation.rate_surface_density.disks.Blitz2006.F90
1. Use tabulations to speed up molecular hydrogen cooling function calculations.
2. Use analytic solution for transition radius in Blitz2006 star formation rate algorithm.
=> Further optimization of baryonic physics models

perl/Galacticus/Build/SourceTree/Process/SourceDigest.pm
When a source file is updated, the file hash and composite hash values mmust alwasy be updated.
=> Ensure source digests are updated

doc/Galacticus.bib, source/merger_trees.branching_probability.generalized_Press_Schechter.F90, source/merger_trees.build.controller.constrained.F90, source/merger_trees.build.controller.filtered.F90, source/merger_trees.build.controller.single_step.F90, source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.F90, source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.midpoint.Brownian_bridge.F90, source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.midpoint.F90, source/structure_formation.excursion_sets.first_crossing_distribution.linear_barrier.Brownian_bridge.F90, source/tasks.evolve_forests.F90, source/tests.merger_tree_branching.F90
Corrects the residual variance and effective offsets in the numerical Brownian bridge solver to correctly condition on the intermediate point in the trajectory.
Also introduces an analytic solution for Brownian bridges with linear barriers.
=> Fix mathematical implementation of Brownian bridge solutions

source/cooling.cooling_function.F90, source/interface.CAMB.F90, source/interface.CLASS.F90, source/interface.FSPS.F90, source/nodes.property_extractor.CGM_cooling_function.F90
Allows output of the cooling function at a specified set of radii. Can also output the total hydrogen density, $n_\mathrm{H}$, at those radii.
=> Add a `nodePropertyExtractor` to output the cooling function in the CGM

perl/Galacticus/Build/SourceTree/Process/InputParametersValidate.pm, perl/Galacticus/Build/SourceTree/Process/ObjectBuilder.pm, source/intergalactic_medium.state.file.F90, source/output.analyses.mass_function_stellar.Bernardi_SDSS.F90, source/output.analyses.mass_function_stellar.GAMA.F90, source/output.analyses.mass_function_stellar.PRIMUS.F90, source/output.analyses.mass_function_stellar.SDSS.F90, source/output.analyses.mass_function_stellar.UKIDSS_UDS.F90, source/output.analyses.mass_function_stellar.ULTRAVISTA.F90, source/output.analyses.mass_function_stellar.VIPERS.F90, source/output.analyses.mass_function_stellar.ZFOURGE.F90, source/posterior_sampling.simulation.particle_swarm.F90, source/statistics.distributions.normal.F90, source/utility.input_parameters.F90
Adds some missing `objectDestructor` directives to avoid memory leaks
=> Fix memory leaks

source/accretion.halo.cold_mode.F90, source/cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90
Added a temperatureCold to accretion.halo.cold_mode.F90
Set minimum temperature checks for cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90
=> Changes to accretion.halo.cold_mode.F90 and cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm, source/mass_distributions.Gaussian_ellipsoid.F90, source/mass_distributions.cylindrical.exponential_disk.F90, source/merger_trees.evolve.timesteps.record_evolution.F90, source/nodes.operators.physics.halo_angular_momentum.Vitvitska2002.F90, source/satellites.merging.virial_orbits.Jiang2014.F90, source/stellar_astrophysics.supernovae_type_Ia.Nagashima2005.F90, source/stellar_astrophysics.tracks.file.F90, testSuite/test-satellite-distance-minimum.pl, testSuite/test-treeFilterLabels.pl
Focused on start-up time:
- Stores slow calculations to file for fast re-use;
- Delays reading of large datasets until needed;
- Avoid excessive destructor calls;
- Avoid pointless use of `trim()` on `varying_string` objects.
=> Further optimization improvements

.github/workflows/cicd.yml, source/star_formation.histories.adaptive.F90, testSuite/regressions/adaptiveSFHLengths.py, testSuite/regressions/adaptiveSFHLengths.xml
Function existed, bur was not linked to a method. Includes a regression test case.
=> Add missing `update` method to `starFormationHistoryAdsptive` class

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
This is intended to avoid race conditions that could occur if multiple threads are attempting to add a default instance of the class to the parameter file simultaneously, which I suspect can lead to errors where the name of the selected instance of the class becomes corrupted.
=> Use OpenMP locks when building class objects from the parameter file

perl/Galacticus/Build/Components/TreeNodes/CreateDestroy.pm, testSuite/parameters/memoryLeakFormationHalos.xml, testSuite/test-memory-leaks.pl
This avoids a memory leak of these formation nodes.
=> Destroy formation nodes when their associated node is destroyed

source/interface.CLASS.F90, source/structure_formation.cosmological_mass_variance.filtered_power_spectrum.F90, testSuite/test-methods.xml
Makes use of CLASS to find the relation between $A_\mathrm{s}$ and $\sigma_8$.
=> Add functionality to normalize the power spectrum via the $A_\mathrm{s}$ parameter

source/structure_formation.power_spectrum.primordial.transferred.file.F90, source/utility.IO.HDF5.F90
* Provide names of attributes when reporting attribute type mismatch errors
* When file version numbers do not match provide guidance on what was expected
=> Fix power spectrum error reporting

source/structure_formation.transfer_function.file.F90, source/tests.halo_mass_function.Reed2007.F90
Test for zero and negative values, reporting errors if these are detected.
Add an option to interpolate in the absolute value of the transfer function, such that negative values can then be accepted.
=> Improve handling of tabulated transfer functions with negative values

source/dark_matter_profiles_DMO.NFW.F90, source/tests.dark_matter_profiles.F90
When computing the radius enclosing a tiny mass for NFW profile, the analytic formula is inaccurate due to roundoff errors, which returns effectively zero value. This may lead to floating-point errors when using NFW profile in the heated profile. To avoid this issue, we can make use of the series expansion of the r(M) function.
=> fix: Use series expansion in computing radius enclosing a small mass for NFW profile.

source/hot_halo.ram_pressure_force.relative_position.F90, source/hot_halo.ram_pressure_stripping.Font2008.F90
This is useful for N-body merger trees where we have position information.
=> Add a ram pressure force class which uses relative positions

parameters/reference/darkMatterHalosStructure.xml, parameters/reference/darkMatterHalosTidalHeating.xml, parameters/reference/evolutionGalaxyFormation.xml, parameters/reference/mergerTrees.xml, parameters/reference/subhaloOrbits.xml, testSuite/parameters/validate_milkyWay.xml
Now matches that published in [Ahvazi et al. (2024)](https://ui.adsabs.harvard.edu/abs/2023arXiv230813599A).
=> Update the reference galaxy evolution model

source/dark_matter_profiles.heating.monotonic.F90, source/nodes.operators.physics.satellite.heating.tidal.F90, source/nodes.operators.physics.satellite_orbits.F90, source/output.analyses.satellite_bound_mass.F90, source/output.analyses.satellite_radius_velocity_maximum.F90, source/output.analyses.satellite_velocity_maximum.F90, source/output.analyses.tidal_tracks.velocity_maximum.F90, source/satellites.tidal_stripping.radius.King1962.F90, source/satellites.tidal_stripping.rate.Zentner2005.F90
Implement an improved model for tidal evolution described in
http://arxiv.org/abs/2403.09597
=> Orbit calibration

source/nodes.property_extractor.satellite.dynamical_time.F90
Added nodePropertyExtractorSatelliteDynamicalTime, a satellite dynamical time extractor class
=> Added nodePropertyExtractorSatelliteDynamicalTime

source/cooling.cooling_radius.simple.F90
This could previously lead to issues in computing the growth rate of the cooling radius.
=> Catch cases where the cooling rate is discontinuous

source/output.analyses.Local_Group.mass_metallicity_relation.F90, source/output.analyses.Local_Group.mass_size_relation.F90, source/output.analyses.Local_Group.mass_velocity_dispersion_relation.F90, source/output.analyses.Local_Group.occupation_fraction.F90, source/output.analyses.Local_Group.stellar_mass_function.F90, source/output.analyses.Local_Group.stellar_mass_halo_mass_relation.F90, source/output.analyses.Sunyaev-Zeldovich_Planck2013.F90
Also correct mis-spelled `constructorAssign` directive.
=> Add missing destructors

source/structure_formation.gravitational_lensing.Takahashi_2011.F90
The magnification table is logarithmically-spaced, so we must avoid zero.
Also uses a hashed-descriptor in the filename for the tabulated lensing magnification distribution - this allows correct handling of dependencies on cosmological parameters and power spectra etc.
=> Avoid attempting to tabulate to zero magnification

source/tasks.evolve_forests.F90
The number of decimal digits is now expanded to ensure that each output time is uniquely represented. Previously, only two decimal digits were displayed, which resulted in duplicate displayed times when outputs differed by less than 0.01Gyr.
=> Improve the formatting of the tree output time messages

parameters/reference/cosmologyMillennium.xml, parameters/reference/darkMatterHalosStructureNBody.xml, parameters/reference/evolutionGalaxyFormationNBody.xml, parameters/reference/powerSpectrumMillennium.xml, source/hot_halo.ram_pressure_force.relative_position.F90
Avoid using a null pointer when determining which host halo to use for computing hot halo ram pressure forces.
=> Avoid segfaults when computing ram pressure forces

source/utility.IO.XML.F90
(cherry picked from commit 500be7a53809f511d49b6aa92c2b668f8f1d2ee6)
=> Correctly handle XML `XInclude` elements with absolute paths

source/utility.MPI.F90, source/utility.memory_reporting.F90
If SLURM has set memory limits (and reports them in its environment variables) we now use those to set the maximum available memory when reporting memory usage. A `NOTE` is displayed to show whether the total memory available was determined from SLURM or from the system.
Also, when running under MPI, the maximum available memory is divided by the number of processes on the node to give an indication of how much is available to each process.
=> Improve memory reporting when running under SLURM

source/galactic.filters.stream_kick.F90
=> Add stream_kick.F90 filter for stream velocity kick.

source/nodes.operators.physics.halo_angular_momentum_random.F90
The vector angular momentum is assumed to always point along the first axis (since this model makes no physical prediction for the direction of the vector).
Setting the vector angular momentum is important to ensure that the angular momentum evolves correctly (since the evolution in the magnitude of the angular momentum is determined from the evolution in the vector components).
=> Set the vector angular momentum (if possible) in the `nodeOperatorHaloAngularMomentumRandom` class

source/dark_matter_profiles.structure.concentration.Schneider2015.F90
Previously the mean was just set to the concentration, which would be incorrect if that concentration included scatter.
=> fix: Correctly compute the mean concentration when using the `schneider2015` class

source/galactic.filters.stream_impact.F90
Nodes can never impact a stream at the final output time (since impacts are always computed over the subsequent timestep). Detect the final output time and never pass nodes at or after this time.
=> Never pass nodes at the final output time in the `streamImpact` galactic filter

source/objects.stellar_luminosities.F90
When a broad-band luminosity is requested (e.g. for some output analysis) but is not present a more helpful error message is now displayed. First, the details of the requested and available luminosities are better formatted so make them easier to read. Second, a help message is given suggesting how to resolve the problem. For example: 
```
Fatal error:                                                                                        
unmatched properties for requested stellar luminosity:                             
name                  type     redshift                  
requested: Lyc                   rest     0.4100                                                    
available:                                                                                          
1 of 2 …
```
=> Provide a more helpful error message when a required broad band luminosity is missing

source/merger_trees.evolver.standard.F90, source/merger_trees.operators.prune_lightcone.F90, source/nodes.operators.analyses.assembly_history_heuristics.F90, source/tasks.evolve_forests.F90, source/utility.files.F90
Fixes various memory issues (missing destructs, uninitialized data, dangling pointers).
=> Fix various memory issues

source/output.analyses.mass_size_relation.Shen2003.F90
Erratum is here: https://ui.adsabs.harvard.edu/abs/2007MNRAS.379..400S/abstract
=> Update Shen 2003 mass-size relation to reflect erratum

source/models.likelihoods.galaxy_population.F90, source/posterior_sampling.simulation.differential_evolution.F90
Controlled by a new parameter `reportEvaluationTimes`.
=> Add optional display of evaluation times in the `posteriorSampleLikelihoodGalaxyPopulation` class

.github/workflows/cicd.yml, parameters/reference/structureFormation.xml, python/queueManager.py, scripts/aux/updateMonitor.pl, scripts/aux/watches.xml, source/merger_trees.branching_probability.PCH_plus.F90, source/merger_trees.build.controller.F90, source/merger_trees.build.controller.constrained.F90, source/merger_trees.build.controller.multi.F90, source/merger_trees.build.controller.output_time_snap.F90, source/merger_trees.build.controller.single_step.F90, source/merger_trees.construct.builder.Cole2000.F90, source/merger_trees.operators.regrid_times.F90, source/output.times.F90, source/output.times.list.F90, testSuite/parameters/validate_mergerTreeConvergence.xml, testSuite/validate-mergerTreeConvergence.py
This includes the associated infrastructure and tools needed to make this possible.
=> Add a script to perform convergence tests of merger tree building

source/mass_distributions.spherical.tabulated.F90
This update allows the `massDistributionSphericalTabulated` class to handle distributions with up to 3 parameters.
=> Expand the tabulated spherical mass distribution class to support up to 3 parameters

source/mass_distributions.spherical.F90
Uses a simple (largely untested) model in which the integral is reduced by a factor $f = M(r_\mathrm{orb})/M$ where $M(r)$ is the mass profile of the perturber, $M$ is its total mass, and $r_\mathrm{orb}$ is its orbital radius in its host.
=> Reduce the Chandrasekhar integral (for dynamical friction) in spherical systems to account for the finite size of the perturber

source/nodes.property_extractor.SED.F90, source/nodes.property_extractor.luminosity_emission_line.F90
This includes the ages, metallicities, wavelengths, etc., at which the matrices are constructed. This is useful if these matrices are to be used externally, as it clarifies what information is contained in the matrix.
=> Add some metadata to the matrix files generated to map star formation hsitories to SEDs and emission lines

parameters/reference/warmDarkMatter.xml, source/mass_distributions.F90, source/mass_distributions.spherical.cusp-NFW.F90, source/mass_distributions.spherical.tabulated.F90, source/tests.mass_distributions.tabulated.F90
These handle cases where $r \ll 1$, and where $y^2 \ll r$.
=> Add further limiting cases to the enclosed mass profile for the `massDistributionCuspNFW` class

aux/words.dict, source/mass_distributions.spherical.cored_NFW.F90, source/mass_distributions.spherical.cusp-NFW.F90, source/mass_distributions.spherical.solition_NFW.F90, source/mass_distributions.spherical.tabulated.F90, source/tests.mass_distributions.tabulated.F90
This is a heavily used function (in tidal radius calculations) so is useful to have tabulated solutions for.
=> Add tabulation of the radius enclosing a given mean density

source/dark_matter_profiles.structure.scale.Ludlow2016.analytic.F90
For models with cut-off power spectra, at very low masses we can get $\sigma^2(f M) - \sigma^2(M) = 0$, resulting in floating point exceptions. Catch such cases and use the fall-back scale radius method instead.
=> Catch cases where no solution is available
