perl/Galacticus/Build/Components/Classes/Output.pm

The refactor of output buffer structure in f0f31a1e8cba348f2004d1b4f30d11c39221cb63 lead to the introduction of an off-by-one error when populating those buffers with values from rank-1 properties. This patch fixes that error.

Fix off-by-one bug when populating output buffers with rank-1 properties

---

scripts/build/codeDirectivesParse.pl
source/accretion.halo.F90
source/cooling.cooling_radius.F90
source/cooling.freefall_radii.F90
source/cooling.freefall_time_available.F90
source/cooling.specific_angular_momentum.F90
source/dark_matter_halos.scales.F90
source/dark_matter_profiles.F90
source/dark_matter_profiles_DMO.F90
source/geometry.lightcones.F90
source/hot_halo.outflow_reincorporation.F90
source/satellites.tidal_stripping.radius.F90
source/star_formation.rate_surface_density.disks.F90

The <calculationReset> element is obsolete in functionClass descriptors, but a few instances of it remained. This patch removes all such instances. It also removes the auto-dependency for calculationReset behavior from the codeDirectivesParse.pl script.
Fixes #148.

Removes obsolete <calculationReset> elements

---

source/nodes.property_extractor.star_formation_rate.F90
source/nodes.property_extractor.stellar_feedback_outflow_rate.F90

Adds a nodePropertyExtractor for stellar feedback-driven outflows.
Also fixes incorrect function descriptions and removes an incorrect "quantity" function for the star formation rate nodePropertyExtractor.

Stellar feedback outflow output

---

doc/Galacticus.bib
source/dark_matter_halos.mass_accretion_history.Hearin2021.F90
source/dark_matter_halos.mass_accretion_history.Hearin2021_stochastic.F90

Adds citations to the Andrew Hearin's 2021 paper on halo mass accretion histories now that the paper is submitted.

Add citation to Hearin et al. (2021).

---

source/nodes.operators.physics.halo_spin_random_walk.F90

Adds a random-walk model for assigning halo spins. Does not require a full merger tree, can be applied to smooth mass accretion histories. Matches the distribution function of spins measured by Benson (2017) very well.
The three components of the angular momentum vector are treated as independent Wiener processes with time-dependent variance. Specifically, each component of the angular momentum vector obeys:
$$
J_\mathrm{i}(t_2) = J_\mathrm{i}(t_1) + \left[ \sigma^2 \left( J_\mathrm{v}^2(t_2) - J_\mathrm{v}^2(t_1) \right) \right]^{1/2} N(0,1)
$$
where $J_\mathrm{v}(t) = M_\mathrm{v}(t) V_\mathrm{v}(t) R_\mathrm{v}(t)$ is the characteristic virial angular momentum, $M_\mathrm{v}(t)$, $V_\mathrm{v}(t)$, and $R_\mathrm{v}(t)$ are the virial mass, velocity, and radius respectively, $\sigma^2$ …

Add a random-walk model for halo spin assignment

---

source/tasks.build_SED_tabulations.F90

This allows a single job to be run to generate all of these tabulations prior to running actual calculations that rely on them.

Adds a task which triggers building of any tabulations needed for SED extraction from nodes

---

source/cosmology.functions.F90
source/cosmology.functions.matter_lambda.F90
source/structure_formation.cosmological_mass_variance.filtered_power_spectrum.F90
source/tests.comoving_distance.F90

Add a particle horizon method to the cosmologyFunctions class, that returns the comoving distance to the particle horizon. Option allows truncating the integral for sigma(M) at the particle horizon.

Allow truncating of sigma(M) integral at the particle horizon

---

source/structure_formation.critical_overdensity.renormalized.F90

This class renormalizes another critical overdensity class to ensure that the halo mass function (assumed to depend only on the peak height parameter, υ) is unchanged as some specified mass scale relative to a reference σ(M) implementation. The intention is that this allows for the halo mass function (presumed to be calibrated under the assumption of a top-hat window function) to be unchanged when some other window function is used for σ(M).
Here's an example of the result:
The green line is a _z_=0 halo mass function (using the [Despali et al. (2015)](http://adsabs.harvard.edu/abs/2015arXiv150705627D) fit) assuming a top-hat window function. The red line is the same but computed with a _sharp-_k_ window function and no renormalization - it clearly shifts the mass function at high masses. …

Add a critical overdensity class which renormalizes to account for a non-top-hat window function

---

source/math.hypergeometric_functions.F90

The `pfq()` function fails for these combinations of arguments. This patch introduces special handling of these cases using the analytic forms from Mathematica.

Handle _2F_1([1,4],[2],x) and _2F_1([2,3],[3],x) hypergeometric functions as special cases

---

Makefile
scripts/build/buildProfiler.pl
scripts/build/profiler.sh

Adds a wrapper script to collect timing data on each task run during build. Also adds a script to generate an HTML report of this profiling data which shows critical points in the build (i.e. low build parallelism) and the most expensive task.

Profile build time

---

perl/Fortran/Utils.pm
scripts/build/buildProfiler.pl
scripts/build/sourceDigests.pl

Use regexes to speed up locating comments in source code lines. These are much faster than stepping through each character of the line one at a time.
Also optimize source digest calculation by only parsing source files when necessary.

Optimize code parsing

---

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
scripts/build/buildCode.pl
source/cooling.cooling_function.summation.F90
source/dark_matter_profiles.heating.summation.F90
source/dark_matter_profiles.structure.scale.concentration.F90
source/galactic.filters.all.F90
source/galactic.filters.any.F90
source/galacticus.output.analyses.distribution_normalizer.sequence.F90
source/galacticus.output.analyses.distribution_operator.sequence.F90
source/galacticus.output.analyses.multi.F90
source/galacticus.output.analyses.property_operator.sequence.F90
source/galacticus.output.analyses.weight_operator.sequence.F90
source/geometry.surveys.combined.F90
source/merger_trees.evolve.timesteps.multi.F90
source/merger_trees.filter.all.F90
source/merger_trees.filter.any.F90
source/merger_trees.operators.sequence.F90
source/merger_trees.outputter.multi.F90
source/nBody.import.merge.F90
source/nBody.import.multiple.F90
source/nBody.operator.sequence.F90
source/nodes.operators.multi.F90
source/nodes.property_extractor.multi.F90
source/radiation.summation.F90
source/radiative_transfer.outputter.multi.F90
source/radiative_transfer.source.summation.F90
source/stellar_feedback.outflows.summation.F90
source/stellar_populations.spectra.postprocess.sequence.F90
source/tasks.evolve_forests.F90
source/tasks.multi.F90

State store/restore was broken for a number of reasons:
1. Recent changes in the syntax of embedded XML blocks resulted in missing of directives in preprocessed source which resulted in all default objects being missed in state store/restore.
2. The `darkMatterProfileScaleRadiusConcentration` failed to tag its `darkMatterHaloScaleDefinition` object as `stateStorable`.
3. Code generation for `deepCopyFinalization` had a bug such that some of its code was inserted into the corresponding `deepCopyReset` code instead.

Get the state store/restore infrastructure working again

---

source/merger_trees.construct.build.masses.read.XML.F90
source/merger_trees.construct.read.importer.galacticus.F90
source/meta.tree_processing_times.file.F90
source/models.likelihoods.multivariate_normal.F90
source/models.likelihoods.multivariate_normal.stochastic.F90
source/radiation.intergalactic_background.file.F90
source/tasks.merger_tree_file_builder.F90

This fixes a problem in which the "description" section of some classes would be parsed into a Perl data structure (instead of plain text) because of the presence of XML in the description. This lead to the description not being entered into the documentation.

Escape XML in LaTeX sections so that it is not parsed as XML

---

Makefile
scripts/doc/Build_Documentation.sh
testSuite/test-all.pl
testSuite/test-methods_MPI.xml
testSuite/test-radiativeTransfer-StromgrenSphere_MPI.pl
testSuite/test-stateRestore_MPI.pl

Enables all test suite tests to be submitted simultaneously. All required code is first built, after which all jobs which handle their own submission to PBS are launched in a new thread, after which all PBS jobs are submitted simultaneously. Once PBS jobs are finished the thread is joined and testing is done.
Also adds a test job which compiles documentation and checks for errors.

Improve parallelism of the test suite

---

source/merger_trees.build.controller.F90
source/merger_trees.build.controller.subsample.F90
source/merger_trees.build.controller.uncontrolled.F90
source/merger_trees.construct.builder.Cole2000.F90
source/merger_trees.walkers.tree_construction.F90
testSuite/parameters/mergerTreeBranchNotSubsampled.xml
testSuite/parameters/mergerTreeBranchSubsampled.xml
testSuite/test-branchSubsampling.pl

Add a `mergerTreeBuildController` class which can provide arbitrary control over how merger trees are built. This is now called by the Cole2000 merger tree builder class.
Adds a `mergerTreeBuildController` which performs subsampling of branches based on their mass.

Add functionality for controlling tree building

---

source/merger_trees.build.controller.branchless.F90
source/merger_trees.build.controller.subsample.F90
testSuite/parameters/mergerTreeBranchless.xml
testSuite/test-branchlessTrees.pl

This adds a `mergerTreeBuildController` which enforces construction of the main branch of the tree only - any side branches are left as stubs. This results in a tree such as the one on the left becoming the one of the right:

Add a merger tree build controller which allows for the construction of "branchless" merger trees

---

source/tasks.build_broadband_luminosity_tabulations.F90
testSuite/test-methods.xml

Using a task:
```
<task value="buildBroadbandLuminosityTabulations"/>
```
will trigger tabulation of all broadband luminosity datasets required for the model. This can be used to efficiently tabulate all required broadband luminosities prior to commencing a production run.

Add a task which triggers tabulation of broadband luminosity tables

---

source/dark_matter_halos.spins.F90
source/objects.nodes.components.dark_matter_halo.spin.scalar.F90
source/objects.nodes.components.dark_matter_halo.spin.vector.F90

This is now used when setting ODE solver scales in the halo angular momentum components as it is faster to evaluate and more robust when considering tidally-heated halos

feat: Provide an option to use the Bullock spin parameter definition for halo angular momentum scales

---

source/instruments.filters.F90
source/interface.FSPS.F90
source/merger_trees.outputter.buffer_types.F90
source/merger_trees.outputter.standard.F90
source/nodes.property_extractor.array.F90
source/nodes.property_extractor.integer_scalar.F90
source/nodes.property_extractor.integer_tuple.F90
source/nodes.property_extractor.list.F90
source/nodes.property_extractor.multi.F90
source/nodes.property_extractor.scalar.F90
source/nodes.property_extractor.tuple.F90
source/objects.nodes.components.position.preset.interpolated.F90
source/objects.stellar_luminosities.F90
source/stellar_populations.spectra.FSPS.F90
source/system.downloader.F90
source/utility.locks.F90

Supports adding meta-data to any output property. Uses this new functionality to add effective wavelength and Vega-AB offset meta-data for all output broadband luminosity properties. Vega-AB offsets are now computed internally for all filters.
Closes #46

Support meta-data for output properties

---

source/dark_matter_profiles_DMO.heated.F90

This could lead to extremely slow range expansion.

Prevent root finder range expansion factor from becoming too small

---

source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.spheroid.standard.F90
testSuite/test-inactive_luminosities.pl

Adds parameters which control the minimum metallicity (for gas and stars) in the standard disk and spheroid components. Prior to this, galaxies with very low metallicity could be rate-limited by that metallicity in ODE solver steps. Since we likely do not care about such tiny metallicities it makes sense to introduce some tolerance.
Also removes the factor 0.1 introduced into the absolute tolerance scale for gas mass in the standard spheroid component - this was introduced long ago and seems to be no longer needed, so it makes sense to restore parity with the treatment in the standard disk component.

Add tolerances for minimum metallicity in disk and spheroid components

---

source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.spheroid.standard.F90
source/star_formation.rate_surface_density.disks.Krumholz2009.F90
testSuite/test-methods.xml

This floor lead to discontinuities in the gradient of the star formation rate surface density which can be challenging for numerical integration. Since we now use a tabulation for the molecular fraction there's no real speed advantage to introducing this floor, so it has been removed.

Remove the molecular fraction floor from the krumholz2009 star formation rate surface density class

---

source/dark_matter_profiles_DMO.SIDM.F90
source/dark_matter_profiles_DMO.SIDM.coreNFW.F90
source/tests.dark_matter_profiles.F90

Implements the CoreNFW profile proposed by Jiang et al. (2022), which is the NFW mass profile multiplied by a tanh(r/r_core) factor. Includes a test case.

Add an implementation of the "CoreNFW" approximation to self-interacting dark matter density profiles

---

source/star_formation.rate_surface_density.disks.Blitz2006.F90

Optimizations are:
- Mark the function as unchanged when possible to avoid duplicated calculation;
- Compute the stellar surface density only if needed;
- Split the integration at the radius where the molecular fraction reaches 100% (to avoid the discontinuity in the integrand);
- Use a fast exponentiator for evaluating the pressure term.

Optimize the blitz0026 star formation rate surface density class

---

source/dark_matter_profiles_DMO.SIDM.F90
source/dark_matter_profiles_DMO.SIDM.isothermal.F90
source/interface.GSL.C.multidimensional_minimization.c
source/numerical.multi_dimensional_minimizer.F90
source/tests.dark_matter_profiles.F90
source/tests.multi_dimensional_minimizer.F90

Implements the isothermal core model for SIDM halos from Jiang et al. (2022). Includes only the low-density (pre-core collapse) solution, as the interpretation of the high-density solution(s) remains unclear.

Add the isothermal SIDM model of Jiang et al. (2022)

---

source/dark_matter_profiles.SIDM.F90
source/dark_matter_profiles.SIDM.isothermal.F90
source/dark_matter_profiles.adiabatic_Gnedin2004.F90
source/galactic.structure.utilities.F90
source/tests.dark_matter_profiles.F90
testSuite/parameters/darkMatterProfiles.xml

Follows the approach of Jiang et al. (2022) and can be applied to, for example, adiabatically-contracted density profiles.

Add an implementation of the SIDM isothermal model which operates on non-DMO density profiles

---

source/objects.nodes.F90

For "numeric" properties they must be solved even if marked as inactive, since "numeric" indicates that we are using an ODE solver that does not support inactive property calculation.

fix: Correct logic for when to evaluate properties during differential evolution

---

perl/Galacticus/Build/Components/Components.pm
source/dark_matter_profiles.structure_tasks.F90
source/galactic.structure.F90
source/galactic.structure.standard.F90
source/hot_halo.mass_distribution.F90
source/mass_distributions.cylindrical.F90
source/mass_distributions.cylindrical.Gaussian_slab.F90
source/mass_distributions.cylindrical.Miyamoto_Nagai.F90
source/mass_distributions.cylindrical.exponential_disk.F90
source/nodes.property_extractor.density.F90
source/nodes.property_extractor.velocity_dispersion.F90
source/objects.nodes.F90
source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.disk.standard.bound_functions.Inc
source/objects.nodes.components.hot_halo.cold_mode.structure_tasks.F90
source/objects.nodes.components.spheroid.standard.F90
source/objects.nodes.components.spheroid.standard.bound_functions.Inc

This avoids problems with deciding where (in 3D) to evaluate density in non-spherical systems (e.g. disks). It is also consistent with the assumptions of the spherical Jeans equation that we're solving.

Use spherically-averaged densities when computing velocity dispersions

---

perl/Fortran/Utils.pm

Failure to do so was resulting in failure to call deepCopyActions on objects in base functionClass objects.

Ensure that 'variableNames' component of declarations is construted

---

source/accretion.halo.Naoz_Barkana_2007.F90
source/accretion.halo.simple.F90
source/chemical.reaction_rates.hydrogen.F90
source/cooling.cooling_function.molecular_hydrogen_Galli_Palla.F90
source/galactic_structure.radius_solver.equilibrium.F90
source/mass_distributions.cylindrical.F90
source/objects.chemical_abundances.F90
source/objects.nodes.components.hot_halo.standard.F90

Major change is to correctly account for exchange of metals and chemicals between the hot halo and unaccrated mass reservoirs. These must be accounted for explicitly as gas is moved between these reservoirs due to a time-varying filtering mass.
Various other minor fixes also.
Adds output of hot halo chemical masses.

Fix issues related to molecular hydrogen calculations

---

source/dark_matter_profiles_DMO.Burkert.F90
source/dark_matter_profiles_DMO.Einasto.F90
source/dark_matter_profiles_DMO.SIDM.coreNFW.F90
source/dark_matter_profiles_DMO.SIDM.isothermal.F90
source/dark_matter_profiles_DMO.truncated.F90

Several of the `darkMatterProfileDMO` classes were missing implementations of the `radiusCircularVelocityMaximum` method. This patch fixes those omissions.

Add missing "radiusCircularVelocityMaximum" methods to darkMatterProfileDMO classes

---

.github/workflows/testMiscMPI.yml
parameters/tutorials/mcmcConfig.xml
source/models.likelihoods.base_parameters.F90
source/output.analyses.HI_vs_halo_mass_relation.ALFALFA_Padmanabhan_2017.F90
source/output.analyses.Local_Group_mass_functions.F90
source/output.analyses.Sunyaev-Zeldovich_Planck2013.F90
source/output.analyses.correlation_function.Hearin2014_SDSS.F90
source/output.analyses.galaxy_sizes_SDSS.F90
source/output.analyses.mass_function_HI.ALFALFA_Martin2010.F90
source/output.analyses.mass_function_HI.F90
source/output.analyses.mass_function_stellar.Bernardi_SDSS.F90
source/output.analyses.mass_function_stellar.F90
source/output.analyses.mass_function_stellar.GAMA.F90
source/output.analyses.mass_function_stellar.PRIMUS.F90
source/output.analyses.mass_function_stellar.SDSS.F90
source/output.analyses.mass_function_stellar.UKIDSS_UDS.F90
source/output.analyses.mass_function_stellar.ULTRAVISTA.F90
source/output.analyses.mass_function_stellar.VIPERS.F90
source/output.analyses.mass_function_stellar.ZFOURGE.F90
source/output.analyses.mass_metallicity_relation.Andrews2013.F90
source/output.analyses.mass_metallicity_relation.Blanc2019.F90
source/output.analyses.morphological_fraction.GAMA_Moffett2016.F90
source/output.analyses.quiescent_fraction.F90
source/output.analyses.quiescent_fraction.Wagner2016.F90
source/output.analyses.star_forming_main_sequence.F90
source/output.analyses.star_forming_main_sequence.Schreiber2015.F90
source/output.analyses.star_forming_main_sequence.Wagner2016.F90
source/output.analyses.stellar_vs_halo_mass_relation.COSMOS_Leauthaud2012.F90

It's necessary to use a copy constructor when walking the parameter tree so that OpenMP locks associated with parameter objects are correctly handled.

Fix a bug in parameter tree traversal

---

source/numerical.root_finder.F90
source/objects.tables.F90
source/star_formation.rate_surface_density.disks.Blitz2006.F90
source/star_formation.rate_surface_density.disks.F90
source/star_formation.rate_surface_density.disks.Krumholz2009.F90
source/star_formation.rates.disks.integrated_surface_density.F90
source/tests.root_finding.F90

In the `starFormationRateSurfaceDensityDisksKrumholz2009` the outer radius is limited to where the molecular fraction drops to zero (when using the "fast" molecular fraction calculation).
In the `starFormationRateSurfaceDensityDisksBlitz2006` class provide an analytic integral in fully molecular regions.

Optimization of the `starFormationRateSurfaceDensityDisksBlitz2006` and `starFormationRateSurfaceDensityDisksKrumholz2009` classes

---

source/error.F90
source/numerical.integration.F90
source/numerical.root_finder.F90
source/tests.root_finding.F90

A thread-safe wrapper around the GSL library error handler exists in Galacticus. This patch causes it to be used throughout.
Resolves #194

fix: Use the thread-safe GSL error handler throughout

---

source/structure_formation.power_spectrum.variance.window_function.hyperbolic_tangent.F90

Compared to the ETHOS or smooth-k filter, the hyperbolic tangent filter can deal with a power spectrum that is more sharply suppressed on small scales. When the smoothing scale is below the half-mode scale, this new filter can mitigate the artificial contribution to the cosmic variance from large-scale power.

Implement a hyperbolic tangent power spectrum window function.

---

source/dark_matter_profiles.structure_tasks.F90
source/galactic.structure.standard.F90

The `galacticStructureStandard` class uses a shortcut when computing the radius enclosing a given mass if the mass requested is dark matter only. Previously this used a different `darkMatterProfileClass` object for this calculation then for corresponding calculations of the mass within a given radius. In some instances this could lead to inconsistent results.
This patch avoids this by using the same `darkMatterProfileClass` object for both calculations.

fix: Use consistent `darkMatterProfileClass` object for galactic structure calculations

---

source/dark_matter_profiles.structure_tasks.F90

Previously used density at radius instead of within radius.

Correct bug in spherical averaged density

---

source/numerical.root_finder.F90

When expanding the bracketing range prior to root finding, when possible shift the lower/upper end of the range to keep the bracket as narrow as possible. This is possible if the expected sign of the root function is known in each limit.

Optimize root finding

---

source/galactic_structure.radius_solver.equilibrium.F90
source/nodes.property_extractor.velocity_dispersion.F90
source/output.analyses.Local_Group.mass_velocity_dispersion_relation.F90

Handle cases where strongly heated halos have no viable solution for the initial guess at galactic structure radii.
Allow control over the tolerance used in velocity dispersion calculations.

Fix issues in SIDM models

---

source/output.analyses.Local_Group.occupation_fraction.F90
source/output.analyses.mean_function_1d.F90
source/output.analyses.property_operator.boolean.F90
source/radiation.intergalactic_background.file.F90

This requires having the `outputAnalysisPropertyOperatorBoolean` class optionally return a small non-zero value instead of precisely zero (for unoccupied subhalos in this case). A precise value causes the result to be ignored by the `outputAnalysisMeanFunction1D` class, which is not what we want.

Correct calculation of Local Group occupation fraction

---

source/chemical.reaction_rates.hydrogen.F90

This is necessary as GSL functions are not thread safe.

Use threadprivate interpolators for molecular hydrogen cross-sections

---

Makefile
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
source/utility.OpenMP.F90
source/utility.OpenMP.workaround.c

In `GLIBC >= 2.34` the functionality `libpthread` is absorbed into `libc`. This results in statically-linked Fortran codes not having `pthread_mutex_destroy()` linked into them. This adds a workaround by including a dummy C function that calls `pthread_mutex_destroy()` (but which itself is never called) for force `pthread_mutex_destroy()` to be linked.

Add a workaround for missing `pthread_mutex_destroy()` function in `GLIBC >= 2.34`

---

source/access.c
source/intergalactic_medium.filtering_mass.Gnedin2000.F90
source/star_formation.rate_surface_density.disks.Blitz2006.F90
source/utility.files.F90

When building the Blitz2006 star formation rate integrals table, we now have the correct sequence of file locking to avoid multiple threads attempting to create the table simultaneously.

Correct file locking logic

---

parameters/reference/evolutionGalaxyFormation.xml
source/dark_matter_profiles_DMO.accretion_flow.F90
source/dark_matter_profiles_DMO.heated.monotonic.F90
source/merger_trees.evolve.timesteps.F90
source/merger_trees.evolve.timesteps.host_tidal_mass_loss.F90
source/merger_trees.evolve.timesteps.multi.F90
source/merger_trees.evolver.standard.F90
testSuite/parameters/impulsiveHeating.xml

Two classes, `darkMatterProfileDMOHeatedMonotonic` and `darkMatterProfileDMOAccretionFlow`, were failing to reset some of the memoized data structures inherited from the `darkMatterProfileGeneric` class, which caused incorrect results to be returned in some cases (e.g. for velocity dispersions).

Reset memoized data in the `darkMatterProfileGeneric` class

---

parameters/reference/evolutionGalaxyFormation.xml
source/merger_trees.evolve.timesteps.F90
source/merger_trees.evolve.timesteps.host_tidal_mass_loss.F90
source/merger_trees.evolve.timesteps.multi.F90
source/merger_trees.evolver.standard.F90
testSuite/parameters/impulsiveHeating.xml

If tree evolution is using the `backtrackToSatellites` option, this timestep limiter could lead to extremely tiny timesteps for a satellite as it is allowed to evolve only a slight amount beyond the time of its host. This fix prevents this by refusing the evolve the satellite (if this class is the limiting factor in evolution) unless the step that can be taken is a sufficiently large fraction of the mass loss timescale. If a step is refused, this will force the host halo to evolve instead. This evoids tiny timesteps.

Prevent the `mergerTreeEvolveTimestepHostTidalMassLoss` from taking tiny timesteps

---

.github/workflows/benchmarks.yml
.github/workflows/buildCode.yml
.github/workflows/testCosmology.yml
.github/workflows/testRegressions.yml
.github/workflows/validate.yml

In this test `Galacticus.exe` is built by one workflow, another workflow is triggered by the completion of this and just uses the `Galacticus.exe` artifact from the first workflow, without needing to rebuild it itself.

Test using the `workflow_run` dispatch for GitHub Actions

---

source/chemical.reaction_rates.utilities.F90
source/cooling.cooling_radius.beta_profile.F90
source/cooling.cooling_radius.isothermal_profile.F90
source/cooling.cooling_radius.simple.F90
source/nodes.property_extractor.ICM_Xray_luminosity.F90
source/nodes.property_extractor.ICM_Xray_temperature.F90
source/nodes.property_extractor.ICM_cooling_power_in_band.F90
source/nodes.property_extractor.ICM_optical_depth_LymanAlpha.F90

Previously the mean chemical density was erroneously used instead of the radius-dependent density.

Correct chemical densities in cooling calculations

---

source/gslODEInitVal2/driver2.c
source/gslODEInitVal2/gsl_odeiv2.h
source/merger_trees.evolve.profiler.F90
source/merger_trees.evolve.profiler.null.F90
source/merger_trees.evolve.profiler.simple.F90
source/merger_trees.evolve.profiler.tiny_steps.F90
source/merger_trees.evolver.standard.F90
source/merger_trees.node_evolver.standard.F90
source/numerical.ODE_solver.F90

Provides additional information to profilers. Adds a new `mergerTreeEvolveProfilerTinySteps` class which profiles the causes of tiny timesteps.

Expand timestep profiler functionality

---

perl/Galacticus/Build/SourceTree/Parse/Declarations.pm

In some instances (e.g. `procedure(double precision)`) paratheses were incorrectly parsed, resulting in invalid code generation.

Fix bug in the parsing of declarations

---

perl/Galacticus/Build/SourceTree/Parse/Directives.pm
perl/Galacticus/Build/SourceTree/Parse/ModuleUses.pm
perl/Galacticus/Build/SourceTree/Parse/OpenMP.pm
perl/Galacticus/Build/SourceTree/Process/InputParametersValidate.pm
perl/Galacticus/Build/SourceTree/Process/ObjectBuilder.pm

This was broken by the recently-added preprocessing of `!$omp parallel` directives.
Also adds source location descriptors for other preprocessor directives.

Correct numbering of lines in preprocessed source files

---

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm

Deep copy of linked lists could be duplicated (leading incorrect reference counts to the objects in the list and so to memory leaks) if the class contained multiple `declaration` sections. This fix ensures that only  a single deep copy of linked lists can occur.

Avoid duplicating link list deep copies

---

source/star_formation.rate_surface_density.disks.Krumholz2009.F90

These caused floating point exceptions. Now the star formation rate is simply set to zero in such cases.

Catch disks with tiny gas densities

---

parameters/reference/evolutionGalaxyFormation.xml
source/chemical.reaction_rates.F90
source/chemical.reaction_rates.hydrogen.F90
source/chemical.reaction_rates.zero.F90
source/hot_halo.mass_distribution.F90
source/hot_halo.mass_distribution.beta_profile.F90
source/mass_distributions.F90
source/mass_distributions.spherical.beta_profile.F90
source/nodes.operators.physics.CGM.chemistry.F90
source/objects.nodes.components.hot_halo.standard.F90
source/tests.mass_distributions.F90

Computes an estimate of the "clumping factor" boost to two-body reaction rates based on the hot halo density profile. Also accounts for the density profile when estimating column densities for self-shielding calculations.
Also, switch to using the more up to date Faucher-Giguere (2020) model for the intergalactic background radiation.

Account for hot halo density profile in molecular hydrogen calculations

---

source/tasks.evolve_forests.work_share.first_come_first_served.F90
source/utility.MPI.F90

Avoids a segfault during finalization (possible compiler bug).

Add a reset method to MPI counters

---

source/events.subhalo_promotion.F90
source/merger_trees.evolve.timesteps.multi.F90

In this case, we set the merging time back to infinity, and the time until destruction to a negative value such that neither merging nor destruction can occur for such a halo (as these are not defined processes for isolated halos).

Reset satellite timescales when a subhalo is promoted to an isolated halo

---

source/structure_formation.cosmological_mass_variance.filtered_power_spectrum.F90
testSuite/parameters/constrainHaloMassFunction.xml

Adds a further split in the integral for σ(M) at a wavenumber corresponding to a few times the inverse of the top-hat radius. Since window functions are expected to cut off above this wavenumber this can help to capture the peak in the integrand (which, otherwise, was very occassionally not captured). As this results is multiple different wavenumber splits for these integrals, we now handle this in a more general way, first generating a list of wavenumbers at which to split, sorting these, and integrating each resulting interval individually.

Make integration of σ(M) more robust

---

source/tasks.evolve_forests.F90
source/tasks.evolve_forests.work_share.F90
source/tasks.evolve_forests.work_share.first_come_first_served.F90
source/tests.MPI.F90
source/utility.MPI.F90

Where possible, the counter is incremented by the number of OpenMP threads waiting to increment in a single MPI call. The resulting set of increments are then handed out to each OpenMP process. This reduces the volume of MPI RMA calls, thereby improving latency.

Improve latency of MPI counters

---

perl/Galacticus/Build/SourceTree/Process/ObjectBuilder.pm
source/utility.input_parameters.F90

First, warnings about default parameters are now issued only from the master process when running under MPI (to avoid large numbers of duplicated messages). Second, an access to the FoX library that occured outside of a required OpenMP critical section is now placed within such a critical section.

Fixes to input parameter handling

---

source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.F90
source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.midpoint.F90

The progress bar is inaccurate when we use multiple MPI processes and `self%coordinatedMPI_` is `.true.`.

Fix an issue that the progress bar is inaccurate when solving the excursion sets problem with MPI

---

source/pFq/pfq.new.f

Two constant variables that were set at run time are not instead set during initialization to avoid these spurious reports.

Avoid spurious data race reports from the hypergeometric `pFq` function

---

source/interface.CAMB.F90
source/interface.CLASS.F90

This is now done manually for the CAMB and CLASS interfaces where we do not have full control over the file names.

Use temporary file names that are unique across OpenMP and MPI threads/processes

---

perl/Galacticus/Build/Components/Implementations/CreateDestroy.pm
source/objects.abundances.F90
source/objects.chemical_abundances.F90
source/objects.kepler_orbits.F90
source/objects.stellar_luminosities.F90
source/objects.tensors.rank2.dimension3.symmetric.F90
source/utility.input_parameters.F90

There were a handful of cases where this had been missing previously.

Add OpenMP critical sections around accesses to the FoX library

---

scripts/build/libraryInterfaces.pl
source/structure_formation.cosmological_mass_variance.filtered_power_spectrum.F90
source/structure_formation.transfer_function.AxionCAMB.F90
source/structure_formation.transfer_function.CAMB.F90
source/structure_formation.transfer_function.CLASS_CDM.F90
source/structure_formation.transfer_function.F90
source/structure_formation.transfer_function.file.F90

This makes integration more robust for oscillating transfer functions for example.

Allow σ(M) integral to be split at local minima of the transfer function

---

perl/Galacticus/Build/SourceTree/Parse/Declarations.pm
perl/Galacticus/Build/SourceTree/Process/ObjectBuilder.pm
source/cooling.cooling_function.summation.F90
source/output.analyses.stellar_vs_halo_mass_relation.COSMOS_Leauthaud2012.F90
source/utility.MPI.F90

When computing the logarithmic gradient of the cooling function with respect to density in the `coolingFunctionSummation` class we were doing: 
$$
\frac{\mathrm{d}\log \Lambda}{\mathrm{d}\log n} = \frac{n}{\Lambda} \sum \frac{\mathrm{d}\log \Lambda_i}{\mathrm{d}\log n} \frac{\Lambda_i}{n}
$$
But, since the density, $n$, is constant there's no need to do this, and we then also avoid floating point errors if the density is zero.

Avoid unnecessary divide/multiply in summation cooling function

---

source/mass_distributions.Gaussian_ellipsoid.F90
source/mass_distributions.spherical.Sersic.F90
source/math.linear_algebra.F90

We do this by explicitly allocating and deallocating, and by not using function results in expressions (but instead assigning them to variables first). These approaches should no longer be necessary when gfortran finalization is fully implemented.

Avoid memory leaks with interpolators and matrices

---

source/utility.input_parameters.F90
testSuite/test-allowed-parameters.pl

Makes it easier to track down where the problem is in the parameter file.

Report the path to a parameter when resporting an unknown parameter name

---

aux/words.dict
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
source/models.likelihoods.base_parameters.F90
source/utility.input_parameters.F90

Fixes memory leaks due to:
* Traversal of sub-parameters;
* Use of array constructors.
Both are workarounds until finalization is fully implemented.

Fix memory leaks

---

source/dark_matter_profiles_DMO.SIDM.isothermal.F90
source/galactic.structure.standard.F90

In the `galacticStructureStandard` class we make use of a stack to store the state of the query (e.g. radius, mass and component types, etc.). This is necessary as the state must be accessible with sub-module scope (for some of the numerical solvers used), and these functions can be called recursively with different state. So, we must push and pop from a stack in order to avoid overwriting state from previous invocations.
This was previously implemented as an allocatable array of states, which was expanded as needed. This can cause problems though. If variables from the state stack have been passed (by reference) to some function, which then invokes the `galacticStructureStandard` class itself, and if that causes the stack to be expanded, those variables passed by reference now point to …

Use a linked-list of `galacticStructureStandard` state

---

source/satellites.tidal_stripping.radius.King1962.F90

When calculating the tidal radius, Galacticus will compute the eigenvectors of the tidal tensor and project the tidal acceleration in the direction of the eigenvector with the largest eigenvalue.
```
tidalFieldRadial                =-abs(tidalTensor%vectorProject(tidalTensorEigenVectorComponents(maxloc(tidalTensorEigenValueComponents,dim=1),:))) &
&                           *(                                                                                                                 &
&                             +kilo                                                                                                            &
&                             *gigaYear                                                                                                        &
& …
```

Fix bugs in the calculations of tidal radius

---

source/nodes.operators.analyses.mass_bound_maximum.F90
source/nodes.property_extractor.mass_bound_maximum.F90

Adds a `nodeOperator` and a `nodePropertyExtractor` to allow tracking and output of the peak bound mass ever attained by each halo.

Track peak bound masses of nodes

---

source/dark_matter_profiles.generic.F90
source/dark_matter_profiles_DMO.heated.F90

For heated dark matter profiles, the radius velocity dispersion is computed by numerically integrating the Jeans equation:
$\sigma_r(r) = \frac{1}{\rho(r)}\int_r^{r^{\mathrm{max}}} \rho(r) \frac{\mathrm{G} M(r)}{r^2} \mathrm{d} r.$
This is time consuming because one needs to solve for $\rho(r)$ frequently. If we do the above integration with respect to the initial radius $r_i$ which is related to $r$ by
$-\frac{G M}{2 r_i} + \Delta E_h(r_i) = -\frac{G M}{2 r},$
it will be much faster, i.e.
$\sigma_r(r) =\frac{1}{\rho(r)}\int_{r_i}^{r_{i}^{\mathrm{max}}} \rho_i(r_i) \frac{\mathrm{G} M(r_i)}{r_i^2}\left(\frac{r_i}{r}\right)^4 \mathrm{d} r_i$.
Here $\Delta E_h$ is the heating energy on a mass shell with initial radius $r_i$. Then one only needs to compute $\rho(r)$ once and $\rho_i(r_i)$ is …

Improve the calculation of radial velocity dispersion for heated dark matter profile

---

source/nodes.operators.physics.bar_instability.F90
source/nodes.operators.physics.star_formation.disks.F90
source/nodes.operators.physics.star_formation.spheroids.F90

When _not_ solving for luminosities as inactive properties, their are various properties (mass of stars formed, fraction of disk mass retained) that are not used. These are now marked as analytically-solvable (and then simply left at zero) so that they do not get included in the ODE solver.

Improve efficiency of non-inactive evolution

---

source/nodes.operators.physics.satellite_destruction.mass_threshold.F90

Offer helpful advice when this happens. This avoids an infinite loop where a satellite can be staged for destruction but never destroyed.

Detect failure to destroy satellite halos

---

source/structure_formation.cosmological_density_field.F90

The root finder is now stored in `self` so does not need to be constructed/destructed every time.

Optimize the use of the time-of-collapse root finder

---

source/galactic.filters.any_descendant_node.F90
source/galactic.filters.labelled.F90
source/nodes.operators.metadata.label.F90
source/nodes.property_extractor.labels.F90
source/objects.nodes.labels.F90
testSuite/parameters/treeFilterLabels.xml

Provides a `nodeOperator` to apply labels to nodes (based on a `galacticFilter`) during initialization. Also provides some new `galacticFilter`s to check for labels in other nodes, and to apply a filter to all descendant nodes.

Add further node labeling functionality

---

source/tests.parameters.F90
source/utility.input_parameters.F90
testSuite/parameters/testsParameters.xml

For example:
* "`.`" implies the current parameter - so `=[.::parameterName]` refers to a parameter named `parameterName` within the current parameter;
* "`..`" implies the parent parameter - so `=[..::parameterName]` refers to a parameter named `parameterName` in the parent of the current parameter.

Allow relative paths in input parameter evaluated expressions

---

doc/Galacticus.bib
source/dark_matter_profiles.structure.concentration.Diemer-Joyce2019.F90
source/dark_matter_profiles.structure.concentration.WDM.Bose2016.F90
source/dark_matter_profiles.structure.concentration.WDM.F90

Implement the fitting function from Bose et al. 2016:
$c_\mathrm{WDM} = c_\mathrm{CDM} \left( 1 + \gamma_1 {M_\mathrm{1/2} \over M_\mathrm{halo}} \right)^{-\gamma_2} (1+z)^{\beta(z)},$
where $\gamma_1=60$, $\gamma_2=0.17$, $M_\mathrm{1/2}$ is the mass corresponding to the wavenumber at which the WDM transfer function is suppressed below the CDM transfer function by a factor of 2, $M_\mathrm{halo}$ is the mass of the dark matter halo, and $\beta(z)=0.026 z-0.04$.

Add a new fitting function of the mass-concentration relation for WDM

---

.github/workflows/cicd.yml
perl/Galacticus/Build/Components/Classes/Evolve.pm
perl/Galacticus/Build/Components/Properties/Evolve.pm
scripts/analysis/debugAnalyzer.pl
scripts/build/libraryDependencies.pl
source/backtrace.c
source/merger_trees.node_evolver.standard.F90
source/tests.debugging.F90
source/tests.debugging.functions.F90
source/utility.debugging.F90

If compiled with the option `-DDEBUGGING` then a call to `debugOn()` will result in detailed information being output to a debug file for every ODE step, including values of all properties, total rates of change, and rates of change contributed by individual functions. Calling `debugOff()` will suspend this output. 
A script `scripts/analysis/debugAnalyzer.pl` is provided to parse this output and format it as CSV files for easy plotting and further analysis.

Add support for detailed debugging output

---

source/dark_matter_profiles.structure.concentration.Schneider2015.F90

Avoids the reference mass decreasing to arbitrarily low masses (before eventually causing a floating point exception). This is an unusual circumstance (as the reference mass is typically large than the actual mass) but can occur, for example, if a misconfigured parameter file is used.

Catch numerical failures in the `darkMatterProfileConcentrationSchneider2015` class

---

source/error.F90
source/interface.GSL.F90
source/structure_formation.cosmological_mass_variance.filtered_power_spectrum.F90

Makes the integration tolerant of round-off and max interval failures if the integrand is tiny. Also in cases where the integral is unexpectedly zero even with a logarithmic integration variable, now attempts to narrow the range of integration to find a non-zero result.

Make integration of $\sigma(M)$ more robust for models with truncated power spectra

---

parameters/reference/mergerTrees.xml
source/error.F90
source/merger_trees.branching_probability.PCH_plus.F90
source/merger_trees.branching_probability.Parkinson_Cole_Helly.F90
source/tests.merger_tree_branching.F90

Round-off errors can be unavoidable at scales below the cut-off scale in models with truncated power spectra.

Allow to tolerate round-off errors in merger tree branching integrals

---

Makefile
source/interface.FSPS.F90

When building FSPS we usually include the compiler option [`-mcmodel=medium`](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) to support a larger memory model for some of the very large static arrays used by FSPS. Arm64 architectures do not have this option, but their [default memory model](https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html) is sufficient anyway. So, simply disable this option when compiling on Arm64.

Fix build of FSPS on Apple M1/M2 chips

---

source/merger_trees.outputter.buffer_types.F90
source/merger_trees.outputter.standard.F90
source/nodes.property_extractor.SED.F90
source/nodes.property_extractor.array.F90
source/nodes.property_extractor.density.F90
source/nodes.property_extractor.density_contrasts.F90
source/nodes.property_extractor.mass_profile.F90
source/nodes.property_extractor.multi.F90
source/nodes.property_extractor.projected_density.F90
source/nodes.property_extractor.projected_mass.F90
source/nodes.property_extractor.rotation_curve.F90
source/nodes.property_extractor.velocity_dispersion.F90

These can also be provided with a description and units information. The `mergerTreeOperatorStandard` class supports this new functionality and will output these numerical column values if they are provided.

Allow `nodePropertyExtractorArray` objects to specify numerical column values

---

source/merger_trees.build.controller.F90
source/merger_trees.build.controller.branchless.F90
source/merger_trees.build.controller.constrained.F90
source/merger_trees.build.controller.single_step.F90
source/merger_trees.build.controller.subsample.F90
source/merger_trees.build.controller.uncontrolled.F90
source/merger_trees.construct.builder.Cole2000.F90

Halos are labeled as `primary` (sampled directly from the progenitor mass function), `secondary` (inserted to ensure mass conservation in a binary split), or `smooth` (resulting from smooth accretion, i.e. no branching).

Add labeling of progenitor halo origins when using the `singleStep` build controller

---

perl/Galacticus/Build/SourceTree/Process/Enumeration.pm
source/objects.enumeration.F90

This avoids the need for any `same_type_as()` function - it makes no sense to test equality of different enumerations anyway, so this gives some modest speed up.

Generate custom equality operator for each enumeration

---

source/nBody.operator.potential_energy.F90
source/nBody.operator.self_bound.Barnes_Hut.F90
source/nBody.operator.self_bound.F90

Fix two issues:
1. When doing self-bound analysis, the most-bound particle in velocity space is found by searching for the minimum of potential in velocity space (similar to the calculation of gravitational potential in position space). In the current version of Galacticus, the softening velocity (similar to the definition of softening length) is fixed at 1 km/s by default. But this default value may be too large for small halos with typical particle velocity smaller than 1km/s. Instead, we can define a softening velocity as
$v_{\rm softening} = \sqrt{G m_p/r_{\rm softening}},$
where $m_p$ is the particle mass, $r_{\rm softening}$ is the softening length.
2.  When computing the gravitational potential at particle positions, a "omp do" directive is missing, which lead to incorrect results.

Fix nBody operator

---

.github/workflows/cicd.yml
source/stellar_astrophysics.tracks.file.F90
source/stellar_populations.standard.F90
testSuite/parameters/noninstantaneous_recycling.xml
testSuite/test-noninstantaneous-recycling.pl

When tabulating stellar population metal production, the element index is set outside of the OpenMP `parallel` region, so must be copied in to all threads to allow each thread to compute for the correct element.

Copy element index in to OpenMP parallel region

---

source/dark_matter_profiles.structure.concentration.MunozCuartas2011.F90
source/dark_matter_profiles.structure.concentration.Zhao2009.F90
source/output.analyses.HI_vs_halo_mass_relation.ALFALFA_Padmanabhan_2017.F90
source/satellites.merging.virial_orbits.Li2020.F90
source/structure_formation.virial_density_contrast.Bryan_Norman.F90

If the option `allowUnsupportedCosmology` is set to `true` then cosmologies for which [Brayn & Norman (1998)](https://ui.adsabs.harvard.edu/abs/1998ApJ...495...80B/abstract) do not provide a fitting function revert to using the numerical solutions for the spherical top-hat collapse model.

Allow the `virialDensityContrastBryanNorman1998` class to work for arbitrary cosmologies

---

source/accretion_disks.spectra.Hopkins2007.F90
source/system.downloader.F90

Adds the retry options to the `varying_string` version of the `download()` function to match those of the `character` version.
Also adds a keyword to one call to `download()` to ensure that the status option is passed correctly.

Fix behavior of the `download()` function

---

perl/Galacticus/Build/SourceTree/Process/InputParametersValidate.pm
perl/Galacticus/Build/SourceTree/Process/ObjectBuilder.pm
source/intergalactic_medium.state.file.F90
source/utility.input_parameters.F90

- Avoid multiple reinitializations of the globally-known parameter names array
- Avoid excessive destructor calls

Further minor optimizations

---

source/interface.Cloudy.F90
source/system.downloader.F90

Useful as sometimes the source is moved to `old/` several days before the new release source is available.

Allow download of Cloudy from `old/` subdirectory if main directory fails

---

.github/workflows/cicd.yml
source/structure_formation.power_spectrum.nonlinear.CosmicEmu.F90
testSuite/regressions/cosmicEmu.pl
testSuite/regressions/cosmicEmu.xml

Previously if the file already existed (from a previous run) it would not be read, leading to a segfault as the interpolator was uninitialized.

Ensure that CosmicEmu power spectra files are read even if they pre-existed

---

perl/Galacticus/Build/SourceTree/Process/DeepCopyActions.pm
perl/Galacticus/Build/SourceTree/Process/StateStorable.pm
scripts/build/libraryInterfaces.pl

Perl v38 (which now ships with GitHub MacOS runners) has a subtle change in behavior for regexes using grouped alternative matches with sub-matches. This broke behavior in identifying abstract classes in a couple cases. A more robust approach that avoids sub-matches in this case.

Fix broken regex behavior

---

source/black_holes.accretion_rates.F90
source/black_holes.accretion_rates.spheroid_tracking.F90
source/black_holes.accretion_rates.standard.F90
source/merger_trees.outputter.standard.F90
source/nodes.property_extractor.jet_power_black_holes.F90
source/nodes.property_extractor.mass_accretion_rate_black_holes.F90
source/nodes.property_extractor.mass_black_holes.F90
source/nodes.property_extractor.radiative_efficiency_black_holes.F90
source/nodes.property_extractor.radius_black_holes.F90
source/nodes.property_extractor.spin_black_holes.F90
source/objects.nodes.components.black_hole.simple.F90
source/objects.nodes.components.black_hole.standard.F90
testSuite/parameters/bolshoiTestTreesGLC.xml
testSuite/test-methods.xml

This homogenizes the output - all node properties should be output to the `nodeData` group. This supports multiple SMBHs per galaxy.
Additionally, SMBH accretion physics is abstracted out to a `blackHoleAccretionRate` class.

Refactor SMBH property output such that these are output to the `nodeData` group

---

source/galactic.structure.utilities.F90

In the globally-callable constructor function for the `galacticStructure` class, the parameter name `galacticStructure` was misspelled. This could lead to the object being constructed from the wrong entry in the parameter file.

Correct a typo in the name of the `galacticStructure` parameter

---

source/geometry.surveys.mangle.F90

In this case these were a holdover from when objects were shared across threads.

Remove obsoleted OpenMP `critical` sections

---

.github/workflows/cicd.yml
source/merger_trees.outputter.standard.F90
testSuite/regressions/outputRank2ExtendSegFault.xml

When the output buffers must be extended, the `rank1VarLen` and `rank2VarLen` arrays must be extended and their original content copied back in. The was previously not done, resulting in a segfault due to out-of-bounds array access.
Thanks @msbovill for finding this problem!

Fix a segfault associated with output of `rank?VarLen` datasets

---

source/benchmarks.stellar_luminosities.F90
source/stellar_astrophysics.file.F90
source/stellar_astrophysics.supernovae_PopulationIII.zero.F90
source/stellar_astrophysics.supernovae_type_Ia.F90
source/stellar_astrophysics.supernovae_type_Ia.Nagashima2005.F90
source/stellar_astrophysics.supernovae_type_Ia.zero.F90
source/tests.initial_mass_functions.F90
source/tests.stellar_populations.F90
source/tests.stellar_populations.luminosities.F90

* Corrects the implementation of the Nagashima et al. (2005) model for the number of Type Ia SNe as a function of population age/metallicity. It correct the dependence on the initial mass function, adds a missing Jacobian term, and implements the upper limit on the primary.
* In the `stellarAstrophysicsFile` class, extrapolation in initial stellar mass is no longer performed - instead, for masses outside of the available range, stellar properties are truncated to zero. Additionally, no extrapolation in metallicity is made outside of the available range.
* Adds implementations of the `supernovaeTypeIa` and `supernovaePopulationIII` classes that assume zero contributions. This is useful to test the contribution of type Ia SNe to metal enrichment, and to disable Pop III contributions.

Fix various issues related to non-instantaneous evolution of stellar populations

---

.github/workflows/cicd.yml
source/black_holes.accretion_rates.standard.F90
source/dark_matter_profiles.adiabatic_Gnedin2004.F90
source/nodes.property_extractor.galaxy_major_merger_time.F90
source/nodes.property_extractor.jet_power_black_holes.F90
source/nodes.property_extractor.radiative_efficiency_black_holes.F90
source/nodes.property_extractor.radius_black_holes.F90
source/structure_formation.cosmological_density_field.F90
source/tests.DiemerKravtsov2014_concentration.F90

Also remove the context option from the `grep` commands used to search for related warnings and errors. The context option seem to prevent GitHub actions for recognizing a failed step (e.g. if such warnings are present).

Remove unused variables, symbol imports, and mark known initialized variables

---

perl/Galacticus/Build/Components/Classes/CreateDestroy.pm
perl/Galacticus/Build/Components/TreeNodes.pm
source/merger_trees.evolver.standard.F90
source/merger_trees.outputter.standard.F90
source/nodes.operators.analyses.node_formation_time.Cole2000.F90
source/nodes.operators.physics.position.interpolated.F90
source/nodes.operators.physics.satellite_destruction.mass_threshold.F90
source/nodes.operators.physics.satellite_merging.radius_trigger.F90
source/nodes.operators.physics.subsubhalo_promotion.F90
source/nodes.property_extractor.list2D.F90
source/nodes.property_extractor.multi.F90
source/nodes.property_extractor.star_formation_history_masses.F90
source/objects.nodes.components.black_hole.non_central.F90
source/objects.nodes.components.black_hole.simple.F90
source/objects.nodes.components.black_hole.standard.F90
source/objects.nodes.components.hot_halo.standard.F90
source/objects.nodes.components.satellite.orbiting.F90
source/objects.nodes.components.satellite.preset.F90
source/objects.nodes.components.spheroid.standard.F90
source/output.times.list.F90
source/star_formation.histories.F90
source/star_formation.histories.adaptive.F90
source/star_formation.histories.in_situ.F90
source/star_formation.histories.metallicity_split.F90
source/star_formation.histories.null.F90
testSuite/regressions/adaptiveSFHLengths.py
testSuite/regressions/adaptiveSFHLengths.xml

- Correct times output by the `nodePropertyExtractorStarFormationHistoryMasses` class
- Previously these were always the times corresponding to the final output time. They now correspond to the actual time of each output.
- Allows selection of the "all" component, allowing the summed star formation history of disk and spheroid to be output.
- Ensure that adaptive star formation histories are always created with the correct length
- Previously, if a spheroid was created via interrupt at precisely the next output time, the star formation history (created by the `starFormationHistoryAdaptive` class) would be created with times appropriate to the subsequent output time. This resulted in mismatches between the lengths (and times) of star formation histories for some galaxies.
- Expand the test …

Fix adapative star formation history lengths and times

---

perl/Galacticus/Build/SourceTree/Parse/Declarations.pm
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
scripts/build/postprocess.pl

- Add line numbers to individual declarations in the source tree
- When building the tree representation of source code, add line numbers to individual declarations within a `declaration` node. This will allow more fine-grained reporting of line numbers in error messages.
- Refactor function class interface code to include line numbers for declarations
- Function class modules contain interface definitions for functions in the associated submodules. These are now constructed to have line number information present before each declaration in the interface. This allows more accurate and fine-grained line number reporting in compiler error messages.
- Make post-processed compiler error messages more informative
- Messages are now more clear about what is the line number and what is the error …

Fix interface line numbering

---

source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.disk.very_simple.F90
source/objects.nodes.components.spheroid.standard.F90

Without this, the summed star formation history will not match the stellar mass.

Ensure stellar histories are zeroed when zeroing stellar mass due to ODE solver failure

---

source/interface.CAMB.F90

Also adds clean up of some of the temporary files generated that were not previously cleaned.

Use standard function for generating temporary file names for use in CAMB interface

---

source/structure_formation.linear_growth.baryons_darkMatter.F90

This patch is intended to fix an intermittent problem in computing the linear growth factor accounting for baryons. Occasionally this calculation would fail its test with an error messages:
```
M: -> Linear growth: Einstein-de Sitter with baryons
M:      passed: dark matter linear growth factor [k ⟶ ∞ ; z =    0.0]
M:      FAILED: dark matter linear growth factor [k ⟶ 0 ; z =    0.0] [. :0.30554764E+03 ≉ 0.10000000E+01]
M:      passed: dark matter linear growth factor [k ⟶ ∞ ; z =    1.0]
M:      FAILED: dark matter linear growth factor [k ⟶ 0 ; z =    1.0] [. :0.15277382E+03 ≉ 0.50000000E+00]
M:      passed: dark matter linear growth factor [k ⟶ ∞ ; z =    3.0]
M:      FAILED: dark matter linear growth factor [k ⟶ 0 ; z =    3.0] [. :0.76386718E+02 ≉ 0.25000000E+00]
M:      passed: dark …
```

Avoid a possible race condition when computing linear growth factors

---

source/instruments.filters.F90

When outputting filter information (names and effective wavelengths), we previously output the entirety of the allocated array, even if some parts of the array were unpopulated. This can happen as the array is dynamically expanded in size by a factor 2 as needed.
Additionally, this patch ensures that effective wavelengths for all filters have actually been computed before attempting to output them.

Fix uninitialized content in output of filter properties

---

source/output.times.uniform_spacing_in_time.F90
testSuite/test-methods.xml

A mix of time/redshift is allowed for the min/max epoch.

Allow epochs to be specified as redshifts in the `outputTimesUniformSpacingInTime` class

---

.github/workflows/cicd.yml
source/interface.CLASS.F90
source/interface.FSPS.F90

For FSPS, the `Makefile` syntax had changed meaning that our patch for force static builds failed. This is now fixed and we include some level of checking that our patch applied correctly.
For CLASS, the `-static` flag was not being correctly applied to the `LDFLAGS` variable used when linking the code.
The CI/CD workflow now includes checks that these codes are statically linked.

Fix static builds of FSPS and CLASS

---

source/accretion.halo.Naoz_Barkana_2007.F90
source/merger_trees.construct.read.F90

The `alwaysPromoteMostMassive` parameter can only be true if `allowSubhaloPromotions` is also true.

Validate subhalo options

---

.github/workflows/cicd.yml
.github/workflows/testCode.yml
source/hdf5_cFuncs.c
source/hdf5_cTypes.c
source/tests.IO.HDF5.F90
source/utility.IO.HDF5.F90
testSuite/scripts/generate_h5py.py

`h5py` writes strings in this way so it is useful to have this functionality.

Allow reading of variable length string types from HDF5 attributes

---

.github/workflows/cicd.yml
.github/workflows/testModel.yml

This allows import and installation of the IRATE toolkit from a private repo (as the package is no longer officially maintained).

Support installation of the IRATE toolkit for validation of test model outputs

---

source/tests.IO.HDF5.F90
source/utility.IO.HDF5.F90

Requires an iterative approach to find the length of the string as HDF5 provides no means to do this via the API.

Allow read of an HDF5 variable length string to a `varying_string` object

---

source/nodes.property_extractor.position_orbital.F90
source/nodes.property_extractor.velocity_orbital.F90

This is consistent with how orbital positions are computed for output.

Make orbital velocities relative to the eventual host halo when tracking pre-infall orbits

---

.github/workflows/cicd.yml
source/merger_trees.outputter.standard.F90
testSuite/parameters/duplicatedOutputPropertyName.xml
testSuite/test-duplicatedOutputPropertyName.pl

Provides a help message suggesting to check for repeated `nodePropertyExtractor` if duplicated property names are found.
Includes a test suite entry to check that duplicated property name detection is successful.

Add detection of duplicated property names in output

---

doc/Galacticus.bib
source/benchmarks.stellar_luminosities.F90
source/stellar_astrophysics.feedback.F90
source/stellar_astrophysics.feedback.instant_canonical.F90
source/stellar_astrophysics.feedback.standard.F90
source/stellar_astrophysics.supernovae_type_Ia.F90
source/stellar_astrophysics.supernovae_type_Ia.Nagashima2005.F90
source/stellar_astrophysics.supernovae_type_Ia.differential_delay_time_distribution.F90
source/stellar_astrophysics.supernovae_type_Ia.fixed_yield.F90
source/stellar_astrophysics.supernovae_type_Ia.mass_independent_delay_time_distribution.F90
source/stellar_astrophysics.supernovae_type_Ia.power_law_delay_time_distribution.F90
source/stellar_astrophysics.supernovae_type_Ia.power_law_delay_time_distribution_differential.F90
source/stellar_astrophysics.supernovae_type_Ia.zero.F90
source/stellar_populations.initial_mass_functions.Chabrier2001.F90
source/stellar_populations.initial_mass_functions.F90
source/stellar_populations.initial_mass_functions.piecewise_power_law.F90
source/stellar_populations.standard.F90
source/tests.initial_mass_functions.F90
source/tests.stellar_populations.F90
source/tests.stellar_populations.luminosities.F90

* Provides a more flexible means of implementing delay time distributions. The top-level method, `number` still returns the cumulative number of type Ia SNe per secondary star mass interval.
* A new abstract class `supernovaeTypeIaFixedYield` is provided which assumes fixed yields per SNeIa, thereby avoiding the need to reimplement this in all other classes.
* The `supernovaeTypeIaNagashima2005` class now inherits from `supernovaeTypeIaFixedYield` but is otherwise unchanged.
* A new abstract class `supernovaeTypeIaMassIndependentDTD` (inhereting from `supernovaeTypeIaFixedYield`) is provided which assumes a delay time distribution that is independent of secondary star mass. It provides a deferred method `numberCumulative` that simply returns the cumulative number of SNeIa by a given age. …

Refactor the supernovae type Ia delay time distribution class

---

parameters/tutorials/darkMatterOnlySubHalos.xml
perl/Galacticus/Build/SourceTree/Process/Enumeration.pm
source/structure_formation.critical_overdensity.spherical_collapse_baryons_darkMatter_darkEnergy.F90
source/structure_formation.spherical_collapse.solver.baryons_darkMatter_darkEnergy.F90
source/structure_formation.spherical_collapse.solver.collisionlessMatter_cosmologicalConstant.F90
source/tests.spherical_collapse.baryons_dark_matter.F90

* Force use of a finer-grained `CAMB` solution when solving for the linear growth of perturbations including baryons. This avoids problems in integrating over the power spectrum when a coarser-grained solution was used.
* Optimize retabulation of spherical collapse solution when including baryons. When retabulating these solutions, values from the prior solution (if available) are now re-used to avoid wasting time recomputing them.
* Avoid race conditions in file locking for spherical collapse solutions. Previously, testing for the existance/extent of a pre-existing solution file, and the subsequent (re)build of the solution were done within separate locks, allowing for a race condition.
* Allow specification of `energyFixedAt` for the critical overdensity when including baryons in …

Optimize baryonic spherical collapse solvers

---

source/satellites.merging.virial_orbits.Jiang2014.F90

The tables depend on the parameters used for the orbital distribution, so we must use a hashed descriptor in the filename, otherwise the same file is used for al parameter values.

Add a hashed descriptor to the file name for tabulated `virialOrbitsJiang2014` data

---

source/utility.memory_reporting.mallinfo2.c

Failure to do so results in a problem in the pre-processor due to an undefined macro.

On recent MacOS must include `stdlib.h` prior to `malloc.h`

---

source/merger_trees.construct.read.F90
source/merger_trees.operators.prune_by_mass_and_time.F90
source/merger_trees.pruning.utilities.F90
source/objects.nodes.components.satellite.orbiting.F90
source/objects.nodes.components.satellite.standard.F90
testSuite/validate-PonosV.pl

This is necessary as some operators cause orbits to be assigned to non-primary progenitor halos. Without back-propagation of the `satellite` component those orbits (and other satellite properties) will be lost when the primary progenitor of the halo is promoted to it (and, typically, a new orbit is then assigned, which will break the expected correlations between subhalo orbits and any properties of the host halo that depend on them).

`satellite` components must be back-propagated during node promotion

---

source/merger_trees.node_evolver.standard.F90
source/objects.nodes.components.spheroid.standard.F90

Avoids inaccuracies in spheroid properties that can occur when a spheroid first begins to form in a disk.

Remove disk contribution to spheroid scales

---

parameters/reference/evolutionGalaxyFormation.xml
scripts/aux/parametersMigrate.pl
source/nodes.operators.physics.CGM.chemistry.F90
source/objects.nodes.components.hot_halo.standard.F90
source/universe.operators.intergalactic_medium_state_evolve.F90
testSuite/parameters/checkpointingCheckpoints.xml
testSuite/parameters/checkpointingNoCheckpoints.xml
testSuite/parameters/checkpointingResume.xml
testSuite/regressions/adaptiveSFHLengths.xml
testSuite/regressions/issue142.xml
testSuite/regressions/outputRank2ExtendSegFault.xml
testSuite/test-methods.xml

Cosmic microwave background radiation is no longer added internally. This allows more flexibility - the CMB can still be included in the parameter file.

Allow intergalactic background radiation to be fully specified in the parameter file

---

perl/Galacticus/Build/SourceTree/Process/Enumeration.pm

Previously had erroneously inserted the function but after the `return` statement.

Fix generation of enumeration description functions

---

source/satellites.merging.virial_orbits.Jiang2014.F90
testSuite/parameters/constrainDeterministicSpins.xml

Previously writing of the tabulated data was done with only a shared lock, which could lead to conflicts between threads/processes. Now, a shared lock is used for reading, and, if necessary, upgraded to an exclusive lock if the file must be written.

Fix file locking in the `virialOrbitJiang2014` class

---

perl/Galacticus/Build/SourceTree/Process/ThreadSafeIO.pm
source/numerical.root_finder.F90

The numerical root finder code can be called recursively which lead to deadlocks in thread safe IO critical sections. This is now avoided by not doing function evaluations directly inside a `write` statement. Additionally, warning messages are not generated/output if the optional `status` parameter is present - this could have resulted in huge warning logs being produced.
Also adds reporting on reporting on acquisition/release of thread safe IO locks. This is useful for debugging deadlocks.

Fix a deadlock associated with thread safe IO

---

.github/workflows/cicd.yml
perl/Galacticus/Build/SourceTree.pm
perl/Galacticus/Build/SourceTree/Analyze/UseDuplication.pm
perl/Galacticus/Build/SourceTree/Parse/Declarations.pm
perl/Galacticus/Build/SourceTree/Parse/ModuleUses.pm
perl/Galacticus/Build/SourceTree/Parse/Visibilities.pm
perl/Galacticus/Build/SourceTree/Process/ClassDocumentation.pm
perl/Galacticus/Build/SourceTree/Process/Dependencies.pm
perl/Galacticus/Build/SourceTree/Process/EventHooks.pm
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
perl/Galacticus/Build/SourceTree/Process/FunctionClass/Utils.pm
perl/Galacticus/Build/SourceTree/Process/Generics.pm
perl/Galacticus/Build/SourceTree/Process/StateStorable.pm
perl/Sort/Topo.pm

In Perl, the `keys()` function returns keys in a random order. Wherever this is used in our build code we must use `sort(keys())` to ensure deterministic behavior.

Ensure that the preprocessor produces deterministic output

---

scripts/aux/archive.pl
source/geometry.surveys.Bernardi-2013-SDSS.F90
source/geometry.surveys.Li-White-2009-SDSS.F90

- The old [site](https://space.mit.edu/~molly/mangle/download/data/sdss_dr72safe0_res6d.pol.gz) no longer exists.
- Also moves the SDSS DR7 geometry data file download to the dynamic datasets path.
- Also adds a ock on the geometry file for the `surveyGeometryLiWhite2009SDSS` class during download to avoid conflicts

Update the URL for SDSS DR7 geometry data file

---

source/error.F90
source/merger_trees.construct.fully_specified.F90
source/utility.input_parameters.F90

When an error occurs we attempt to close down the HDF5 subsystem. This requires obtaining a lock on the HDF5 subsystem. But, if an error occurs before the lock was initialized then this could cause a segfault due to attempting to access the uninitialized lock. We now check the initialization status before attempting to lock. This could potentially result in a race condition, but since this is already occurring during error, there's only so much that we can do.
Also adds a more useful error message for unparseable parameter files.

Fix segfault during HDF5 close on error

---

source/merger_trees.branching_probability.Parkinson_Cole_Helly.F90
source/merger_trees.construct.builder.Cole2000.F90
source/merger_trees.construct.builder.Cole2000.parallel.F90

Catches various problem of numerical precision and error when building merger trees with truncated power spectra.

Fix truncated power tree build

---

scripts/build/useDependencies.pl
source/geometry.surveys.full_sky.F90
source/geometry.surveys.random_points.F90
source/statistics.points.power_spectrum.F90

Moves the relevant module `use` statements inside preprocessor conditionals making use of the `FFTW3AVAIL` preprocessor macr,o,

Do not attempt to use FFTW3 functions if FFTW is not available

---

source/statistics.distributions.lognormal.F90
source/structure_formation.halo_environment.lognormal.F90

Can now specify the parameters directly instead of specifying the mean and variance.

Add alternative specificiation of log-normal distribution parameters

---

source/nodes.property_extractor.satellite.dynamical_time.F90

Fixed floating point exception in nodePropertyExtractorSatelliteDynamicalTime. Check that both the tidal radius and tidal mass are non zero. If they are zero, return -1.0 to avoid divide by zero.

fix: floating point exception in nodePropertyExtractorSatelliteDynamicalTime

---

testSuite/parameters/concentrationDistributionLudlow2016.xml
testSuite/parameters/concentrationDistributionLudlow2016Environmental.xml

This should have happened along with the [commit](https://github.com/galacticusorg/galacticus/commit/f483d9caf532e5f33cdbe46aad53d076316ec394) that first removed these suffixes, but these two files were apparently missed.

fix: Remove `Method` suffix from parameter names in test suite parameter files

---

source/objects.nodes.components.black_hole.standard.F90

Force negative masses back to te seed mass. This avoids unphysical behavior and later errors.

Catch negative black hole masses in post-step phase

---

source/nodes.operators.analyses.galaxy_gas_major_merger_time.F90
source/nodes.operators.analyses.galaxy_major_merger_time.F90
source/nodes.property_extractor.galaxy_gas_major_merger_time.F90
source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.spheroid.standard.F90

A gas-mass major merger is defined as
$$M_\mathrm{gas, sat} > f M_\mathrm{gas, host}$$
where $M_\mathrm{gas, sat}$, and $M_\mathrm{gas, host}$ are the (disk + spheroid) gas masses of satellite and central respectively, and $f$ is a parameter `ratioGasMajorMerger`.

Add functionality to track and output gas-mass-based major merger times

---

source/star_formation.histories.adaptive.F90

These can be slow to compute when using small timesteps - storing to (and reloading from) file ensures that this overhead is incurred only once.

Store `starFormationHistoryAdaptive` timesteps and mappings to file

---

parameters/reference/evolutionGalaxyFormation.xml

This ensures that, if star formation histories are tracked, the timestepping will be suitably adjusted to ensure that we accurately accumulate star formation to the correct bin. If star formation history is not being tracked this option has no effect.

Include the `starFormationHistory` timestep class in reference models

---

source/models.likelihoods.galaxy_population.F90
source/output.analyses.F90
source/output.analyses.Local_Group.mass_metallicity_relation.F90
source/output.analyses.Local_Group.mass_size_relation.F90
source/output.analyses.Local_Group.mass_velocity_dispersion_relation.F90
source/output.analyses.Local_Group.occupation_fraction.F90
source/output.analyses.Local_Group.stellar_mass_function.F90
source/output.analyses.Local_Group.stellar_mass_halo_mass_relation.F90
source/output.analyses.correlation_function.F90
source/output.analyses.cross_correlator_1d.F90
source/output.analyses.heated_likelihood.F90
source/output.analyses.mean_function_1d.F90
source/output.analyses.morphological_fraction.GAMA_Moffett2016.F90
source/output.analyses.multi.F90
source/output.analyses.null.F90
source/output.analyses.progenitor_mass_functions.F90
source/output.analyses.satellite_bound_mass.F90
source/output.analyses.satellite_radius_velocity_maximum.F90
source/output.analyses.satellite_velocity_maximum.F90
source/output.analyses.scatter_function_1d.F90
source/output.analyses.stellar_vs_halo_mass_relation.COSMOS_Leauthaud2012.F90
source/output.analyses.subhalo_mass_function.F90
source/output.analyses.subhalo_radial_distribution.F90
source/output.analyses.tidal_tracks.velocity_maximum.F90
source/output.analyses.volume_function_1d.F90
source/posterior_sampling.simulation.grid.F90
source/posterior_sampling.state.samples.F90
source/posterior_sampling.state.samples.Latin_hypercube.F90
source/posterior_sampling.state.samples.prior_grid.F90

- Add functionality to output results of analyses to file when doing posterior sampling;
- Provide a more flexible way of sampling posteriors on pre-defined "grids";
- The "grid" can be any set of pre-defined points.
- Current implementations are:
- A uniform grid in the cumulative distribution of each prior;
- A Latin hypercube in the cumulative distribution of each prior.

Add new optimization functionality

---

source/stellar_astrophysics.supernovae_type_Ia.differential_delay_time_distribution.F90
source/stellar_astrophysics.supernovae_type_Ia.mass_independent_delay_time_distribution.F90
source/stellar_astrophysics.supernovae_type_Ia.power_law_delay_time_distribution.F90

The integrand function was previously `contain`ed in the function performing the integral, which can lead to segfaults. The integrand function is now moved outside of the integrating function to avoid this.

Avoid segfault when evaluating delay time integrals

---

source/geometry.surveys.Baldry-2012-GAMA.F90
source/geometry.surveys.Bernardi-2013-SDSS.F90
source/geometry.surveys.Caputi-2011-UKIDSS-UDS.F90
source/geometry.surveys.Davidzon-2013-VIPERS.F90
source/geometry.surveys.Gunawardhana-2013-SDSS.F90
source/geometry.surveys.Hearin-2014-SDSS.F90
source/geometry.surveys.Kelvin-2014-GAMAnear.F90
source/geometry.surveys.Li-White-2009-SDSS.F90
source/geometry.surveys.Local_Group_DES.F90
source/geometry.surveys.Local_Group_SDSS.F90
source/geometry.surveys.Local_Group_classical.F90
source/geometry.surveys.Martin-2010-ALFALFA.F90
source/geometry.surveys.Montero-Dorta-2009-SDSS.F90
source/geometry.surveys.Moustakas-2013-PRIMUS.F90
source/geometry.surveys.Muzzin-2013-ULTRAVISTA.F90
source/geometry.surveys.Tomczak-2014-ZFOURGE.F90
source/output.analyses.utilities.F90

In `outputAnalysis` classes which do not allow single epoch output, explain the problem and suggest a fix, providing the relevant range of redshifts in the error message.

Provide a more helpful error message when single epoch output is not allowed

---

source/merger_trees.evolve.profiler.tiny_steps.F90

This avoids accessing uninitialized data if the `mergerTreeEvolver` is not setting step descriptors.

Ensure that the step descriptor is initialized

---

source/output.times.list.F90
testSuite/parameters/test-output-times.xml
testSuite/test-output-times.pl

The `outputTimesList` class now accept negative times and inteprets them as lookback times. Additionally, it also allows a mixture of `times` and `redshifts` to be specified.

Allow specifying output times via the lookback time

---

source/nodes.operators.filtered.F90
source/nodes.operators.multi.F90

This class applies a set of other `nodeOperator`s, but only if the `treeNode` being operated on passes the supplied `galacticFilter`.

Provide a `nodeOperatorFiltered` class

---

source/satellites.tidal_stripping.rate.Zentner2005.F90
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.005_alpha_1.0_beta_3.0_gamma_1.5.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.01_alpha_1.0_beta_3.0_gamma_1.5.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.05_alpha_1.0_beta_3.0_gamma_0.5.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.05_alpha_1.0_beta_3.0_gamma_1.0.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.2_alpha_1.0_beta_3.0_gamma_0.0.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.2_alpha_1.0_beta_3.0_gamma_0.5.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.2_alpha_1.0_beta_3.0_gamma_1.0.xml
testSuite/parameters/idealizedSubhaloSimulations/tidalTrackBestFit_xc_0.7_ratio_0.4_alpha_1.0_beta_3.0_gamma_0.0.xml

A constant of order unity was ignored in the definition of dynamical timescale, $T_{\rm dyn}$, when computing the tidal mass loss. To be consistent with the definition in the book "Galactic Dynamics" by Binney & Tremaine, $T_{\rm dyn}$ is changed from
$$T_{\rm dyn} = \sqrt{\frac{3 \pi r_{\rm t}^3}{16  G  M_{\rm sub}(r_{\rm t})}}$$
to
$$T_{\rm dyn} = \sqrt{\frac{3 \pi}{16 G  \overline{\rho}(r_{\rm t})}} = 2 \pi \sqrt{\frac{r_{\rm t}^3}{16  G  M_{\rm sub}(r_{\rm t})}}.$$
The updated definition gives a value $\sqrt{4 \pi /3}$ times larger than that from the old definition. Accordingly, the best-fit value of the tidal stripping coefficient $\alpha_{s}$ must also be $\sqrt{4 \pi /3}$ times larger in order to keep the tidal mass loss unchanged, i.e.
$$\frac{d M_{\rm sat}}{dt} = -\alpha_s …

Change the definition of dynamical timescale to follow that in Binney & Tremaine, "Galactic Dynamics".

---

.github/workflows/cicd.yml
source/star_formation.histories.in_situ.F90
testSuite/parameters/test-star-formation-histories-adaptive.xml
testSuite/parameters/test-star-formation-histories-inSitu.xml
testSuite/test-star-formation-histories-adaptive.py
testSuite/test-star-formation-histories-inSitu.py

This now works by wrapping another `starFormationHistory` object, making a duplicate copy of its star formation history, and zeroing out any entries in that duplicate in merging galaxies. This allows the duplicate copy to track in-situ star formation, using whatever binning the wrapped object does. Includes a new test case.

Refactor the `starFormationHistoryInSitu` class

---

source/nodes.operators.metadata.label.F90
source/nodes.property_extractor.tree_indices.F90

Expands the functionality of the `nodeOperatorLabel` class to allow setting of labels based on a `galacticFilter` after each differential evolution step.

Allow filter-based labelling on post-evolution

---

source/mass_distributions.spherical.beta_profile.F90
source/tests.mass_distributions.F90

Includes new entries in the test code to validate these calculations.

Implement missing calculation of beta-profile radial moment for radii of 0 and ∞

---

perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm

If present, default names are now validated and, if invalid, a list of possible valid names is presented.

Add a more helpful error message for invalid default class names

---

source/merger_trees.construct.read.F90

Makes root finder initialization status `threadprivate` to avoid thread conflicts.

Avoid thread conflicts when setting dark matter profile scales read from merger tree files

---

Makefile
scripts/build/codeDirectivesParse.pl
scripts/build/moduleDependencies.pl
scripts/build/useDependencies.pl

If a new source file is added after the code is built, a rescan of files is forced to ensure all dependencies are discovered and created.

Support discovery and build of newly added source files

---

source/atomic.data.F90
source/instruments.filters.F90
source/interface.Local_Group_database.F90
source/objects.chemical_structure.F90
source/stellar_astrophysics.supernovae_type_Ia.fixed_yield.F90

Previously, the `inputPath()` function was called within a `FoX_Access` OpenMP `critical` section. If compiled with `-DTHREADSAFEIO` such `critical` sections are changed into `gfortranInternalIO` `critical` sections. This then caused a deadlock with the same `critical` section within the `displayMessage()` function when diplaying the location of the `datasets` repo. To fix this, the `inputPath()` function is now called prior to entering the `FoX_Access` OpenMP `critical` section.

Avoid deadlocks when reporting the location of the `datasets` repo

---

.github/workflows/profile.yml
source/numerical.interpolation.F90
source/radiation.intergalactic_background.file.F90
source/radiation.intergalactic_background.internal.F90
source/stellar_populations.broad_band_luminosities.standard.F90
source/stellar_populations.spectra.file.F90
source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.F90
source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.midpoint.F90
source/structure_formation.power_spectrum.primordial.transferred.file.F90

If a tabulated power spectrum is increasing in wavenumber at the highest wavenumbers tabulated, and extrapolation in wavenumber in wavenumber is requested, report a warning message that this can be dangerous as it leads to extremely large power on small scales.

Add a warning message for dangerous power spectrum extrapolation

---

source/error.F90

This is useful when running large batches of models to identify precisely which model caused an error.

Report the command line used on error

---

source/accretion_disks.spectra.file.F90
source/nodes.property_extractor.output_selector.F90
testSuite/parameters/outputSelector.xml
testSuite/test-outputSelector.pl

Now accepts an `outputTimes` object allowing more control over which outputs are selected.

Enhance the `nodePropertyExtactorOutputSelector` class

---

source/geometry.lightcones.F90
source/geometry.lightcones.cylindrical.F90
source/geometry.lightcones.null.F90
source/geometry.lightcones.square.F90
source/merger_trees.evolve.timesteps.lightcone_crossing.F90

An initial check was made that the maximum time in the step, `timeEnd`, exceeds the minimum allowed time in the lightcone, but, if this check passed and a lightcone crossing time was found no check was made that _that_ time exceeded the minimum allowed time.

Enforce minimum time in lightcone output

---

source/nodes.property_extractor.lightcone.F90

Peculiar and cosmological redshifts should add according to $1 + z_\mathrm{obs} = (1 + z_\mathrm{cos}) (1 + z_\mathrm{pec})$. The old code contained a bug where $z_\mathrm{obs} = z_\mathrm{cos} + (1 + z_\mathrm{cos}) (1 + z_\mathrm{pec})$. This has been fixed. 
In addition, the code previously used a special relativistic formula for $z_\mathrm{pec}$, valid when the peculiar velocity is purely along the line-of-sight. A full special-relativistic treatment would include time dilation effects (leading to a non-zero $z_\mathrm{pec}$ even for motion in the plane of the sky), but also shifts in the positions (on the sky) where galaxies are observed, due to relativistic aberration. Given these other relativistic effects are being ignored, the code now uses the non-relativistic limit in which …

Fix lightcone redshift observed

---

source/galactic_structure.options.F90
source/galactic_structure.radius_definition.F90

The problem radius specifier is displayed along with an error message explaining the problem, and the problematic part of the specifier highlighted in red. Furthermore, in cases where the problem is an unmatched enumeration member, the allowed enumeration members are listed. Lastly, a link to the relevant section of the documentation is provided.

Provide more informative error messages when failing to parse radius specifiers

---

parameters/reference/cosmologyUNIT.xml
parameters/reference/evolutionGalaxyFormationNBody.xml
parameters/reference/powerSpectrumUNIT.xml
parameters/reference/simulationUNIT.xml
source/nodes.operators.analyses.assembly_history_heuristics.F90
source/objects.nodes.labels.F90

Applies heuristics to detect cases where a halo undergoes an implausible change in mass, and label these.

Add a `nodeOperator` to assess the reliability of merger trees

---

source/merger_trees.construct.builder.Cole2000.F90
source/merger_trees.construct.builder.Cole2000.parallel.F90
source/merger_trees.evolver.threaded.F90

We must use a "global" `nodeIndex`. Using a stack-local `nodeIndex` means that the value is frozen for each task at the time that the task is created. This results in reuse of node index values.
Instead, we now store `nodeIndex` in `self` so that it is shared between all threads.
Additionally, `hostTree` pointers in newly-created `treeNode`s are now set using the `hostTree` pointer from the branch tip node. This avoids a problem (possibly a compiler bug?) when using `tree` directly that caused the `hostTree` pointer to be pointed at seemingly random memory addresses.

Fix parallel tree build indexing

---

source/star_formation.histories.adaptive.F90

In the `starFormationHistoryAdaptive` class the final bin in the SFH can extend past the corresponding output time (due to the finite minimum width of the time bins). When returning the set of times at whicht he SFH is tabulated, limit this final bin to the output time - this ensures that we have the most accurate estimate of the SFR in this bin. Without doing this, the size of the bin is effectively overestimated (since it can be populated with star formation only up to the output time) which would result in an underestimate of the SFR.

Correctly set the final time for the star formation history

---

.github/actions/buildMacOS/action.yml

Requires some changes to paths as installation is to different location.

Update to new MacPort version [guile-1.8](https://ports.macportsorg/port/guile-1.8/)

---

source/star_formation.rate_surface_density.disks.Blitz2006.F90

Previously, objects kept independent copies of this table and never tried to re-read the version from file. This meant that, if the file had been updated, an object would ignore it, recompute the table itself, and write it out. This lead to inefficiency as the new table might not have as large extent as the version it overwrote.
Now, the file is re-read whenever the current table owned by an object is insufficient.

Optimize `starFormationRateSurfaceDensityDisksBlitz2006` table construction

---

perl/Galacticus/Build/SourceTree/Process/EventHooks.pm

Deallocate a derived-type component before reassignment to that derived-type.

Avoid memory leak in events filtering

---

doc/Advanced.tex
source/output.version.F90

The time and date at which the run ends is stored to the attribute `Version/runEndTime` (note that the time and date at which the run starts is now stored to the attribute `Version/runStartTime` instead of `Version/runTime`). Additionally, the duration of the run (in seconds) is stored to the attribute `Version/runDuration`).

Store the run time (and time at which the run ends) to the output file

---

perl/Galacticus/Build/Directives.pm

Previously empty lines such as in this directive section:
```
!![
<inputParameter>
<name>efficiency</name>
<defaultValue>0.01d0</defaultValue>
<description>The efficiency of star formation.</description>
<source>parameters</source>
</inputParameter>
!!]                                                                                                                                                                                                                  
```
would cause XML parsing errors. Now they are ignored.

Ignore empty lines when parsing directives

---

source/display.banner.F90

MPI intercepts `stdout` making it impossible for us to know if we are outputting to a `TTY` or not.

Display the logo only if not compiled using MPI

---

scripts/aux/extractSingleTree.py

Reduces the required memory and speeds up the extraction of a single merger tree from a merger tree file.

fix(perf): only load the necessary parts of each dataset

---

parameters/baryonicPhysicsConfig.xml
parameters/baryonicPhysicsConstrained.xml
scripts/aux/migrations.xml
source/galactic_dynamics.bar_instability.Efstathiou1982.F90
source/galactic_dynamics.bar_instability.Efstathiou1982Tidal.F90
source/galactic_dynamics.bar_instability.F90
source/galactic_dynamics.bar_instability.fixed_timescale.F90
source/galactic_dynamics.bar_instability.stable.F90
source/merger_trees.operators.scale_weight.F90
source/nodes.operators.physics.bar_instability.F90
source/nodes.property_extractor.bar_instability_timescale.F90

Also adds a merger tree operator that scales the weight of each tree by a fixed factor.

Allow different fractions of angular momentum to be retained in disk and spheroid during disk instabilities

---

doc/Advanced.tex
source/utility.memory_reporting.F90

The maximum memory usage (in bytes) is written to an attribute `memoryUsageMaximum` in the `Version` group.

Output the maximum memory usage

---

source/display.F90

MPI breaks our ability to determine if standard output is connected to a file. So, disable colored text to avoid control characters appearing in log files.

Disable colored text output when compiled for MPI

---

perl/Galacticus/Build/SourceTree/Process/SourceIntrospection.pm

Some editors do not add a newline to the last line of the file by default. The lack of a newline can cause problems with parsing the file as this last line may be concatenated with further code - with no newline the concatenated code will be erroneously appended to the last line.

Add a trailing newline to the last line of source files if not present when preprocessing

---

source/nodes.operators.physics.halo_angular_momentum.Vitvitska2002.F90
source/nodes.operators.physics.halo_angular_momentum_random_walk.F90

This can happen in N-body merger trees where a halo can decrease in mass for example. In such cases we assume that the Wiener process describing the angular momentum of the halo is frozen until the characteristic angular momentum begins to grow again.

Catch cases where the characteristic angular momentum decreases with time in the `nodeOperatorHaloAngularMomentumRandomWalk` class

---

.github/workflows/cicd.yml
perl/Galacticus/Build/Components/TreeNodes.pm
source/dark_matter_profiles.structure.scale.concentration.F90
source/merger_trees.build.controller.subsample.F90
source/nodes.operators.clean_subsample_stubs.F90
source/nodes.operators.filtered.main_branch.F90
source/nodes.operators.physics.dark_matter_profile_scale.set.F90
source/objects.nodes.F90
testSuite/parameters/concentrationDistributionJohnson2021.xml
testSuite/parameters/concentrationDistributionJohnson2021Subsample1e7.xml
testSuite/parameters/concentrationDistributionJohnson2021Subsample1e8.xml
testSuite/test-concentration-Johnson2021.pl

- Fix a bug in consolidating branches where the set of nodes consolidated was erroneously shifted by one node.
- Allow the `nodeOperatorDarkMatterProfileScaleSet` class to only update scale radii after some amount of mass growth.
- Add a test of the `darkMatterProfileScaleRadiusJohnson2021` class when subsampling is used.

Add option to leave stubs of subsampled branches in place

---

source/merger_trees.construct.read.F90
source/nodes.operators.physics.halo_angular_momentum.Vitvitska2002.F90
source/objects.kepler_orbits.F90
source/tests.kepler_orbits.F90

* Update orbital angles when propagating an orbit to a new radius;
* Set the ε angle for orbits when reading merger trees from file.

Implement correct treatment of angles in `keplerOrbit` objects

---

.github/actions/buildMacOS/action.yml
parameters/tutorials/galaxyMergerTree.xml
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
scripts/analysis/galaxyMergerTree.py
source/nodes.operators.analyses.galaxy_merger_tree.F90
source/nodes.operators.multi.F90
source/nodes.property_extractor.galaxy_merger_tree.F90
source/nodes.property_extractor.galaxy_merger_tree.indices.F90
source/nodes.property_extractor.galaxy_merger_tree.merger_indices.F90
source/nodes.property_extractor.galaxy_merger_tree.merger_physical.F90
source/nodes.property_extractor.galaxy_merger_tree.objects.F90
source/nodes.property_extractor.galaxy_merger_tree.physical.F90

Includes an example parameter file and plotting script.
A tutorial wiki page is added [here](https://github.com/galacticusorg/galacticus/wiki/Tutorial:-Generating-galaxy-merger-trees).

Add functionality to track and output galaxy merger trees

---

source/merger_trees.operators.prune_hierarchy.F90

This did not affect results as code affected is not reached for extended Press-Schechter merger trees.

Fix a sign error in the `mergerTreeOperatorPruneHierarchy` class

---

source/merger_trees.evolver.standard.F90
source/merger_trees.operators.consolidate_branches.F90

Run times can become extremely long for high resolution trees. At lower resolutions the scaling of run time, $\tau$, with resolution, $M_\mathrm{res}$ is approximately $\tau \propto M_\mathrm{res}^{-1}$ - which is expected since as $M_\mathrm{res}$ decreases there are proportionally more halos in the tree, each of which must be evolved.
When resolution becomes high, not only does the number of halos in the tree increase proportionally, but the frequency of halo mergers increases as a direct result. Each merger requires that differential evolution of the branch be stopped, the merger processed, and then differetial evolution resumed. For each such resumption, we have to process the host halo on the branch, which means determining how far it can be evolved, which means checking each of its …

Optimize evolution of high resolution merger trees

---

source/utility.input_parameters.F90
testSuite/parameters/parametersExtract.xml
testSuite/test-parameters-extract.py

Previously if there were intervening parameters of some different name, or further parameters (of a different name) after the target parameter, the index of an array parameter (used in outputting that parameter to the HDF5 file) was incorrectly computed.

Correctly handle indices on array parameters

---

source/merger_trees.build.controller.main_branch.F90

Sometimes, we do not need to build the full merger trees, e.g. we want to look at the properties of the halos on the main branch. In such cases, building a branchless merger tree will help to significantly speed up the tree building process and save the memory needed to store the tree.
However, some properties of the halos on the main branch may depend on the detailed merger history. For example, if one uses the `ludlow2016` model to determine the halo concentrations, the concentration of a halo will depends on all its progenitors above a certain mass fraction, i.e. not only the progenitors on the main branch. In this case, a branchless merger tree can not be used. To solve this problem, we can keep the nodes on the main branch and all its descendants above a specific mass fraction. This …

Implement a merger tree build controller class which builds trees containing only the main branch and certain descendants

---

.github/workflows/cicd.yml
source/dark_matter_halos.mass_accretion_history.Wechsler2002.F90
source/structure_formation.cosmological_density_field.F90
testSuite/regressions/haloMassFunctionWDMIndeterminateCollapseTime.xml

This can happen if the collapse threshold is never reached due to the upper bound on linear growth (in a universe with a cosmological constant for example). Optionally returns an error status in such cases.
This is now tested for in the `darkMatterHaloMassAccretionHistoryWechsler2002` class and an unphysical value returned in such cases.

Catch cases where the time of collapse for a halo is undefined

---

source/galactic.filters.stellar_mass.F90
source/geometry.surveys.Bernardi-2013-SDSS.F90

This ensures consistency with the stellar mass retrieved by the `nodePropertyExtractorMassStellar` class which is important for `outputAnalysis` classes to ensure that any masses used are consist in the analysis and any filter applied prior to analyzing.

Make the `galacticFilterStellarMass` retrieve the stellar mass from a node's `massDistribution`

---

source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.disk.standard.data.F90
source/objects.nodes.components.disk.very_simple.size.F90
source/objects.nodes.components.disk.very_simple.size.data.F90

These are no longer needed after the [recent refactoring](https://github.com/galacticusorg/galacticus/commit/9caa7c7d42304bbc9a5631e33267f10de814a7c1) of the `massDistribution` class.
The associated `calculationReset` tasks are also removed.

Remove memoized structure variables

---

source/merger_trees.construct.read.F90
source/merger_trees.construct.read.importer.galacticus.F90

Previously incorrectly checked for `position` instead of  `scaleRadius`.

Fix the name of a dataset used in an importer function

---

source/merger_trees.construct.read.F90

Previously a race condition existed in which if a thread did not find the requested tree in the next merger tree file (even though it existed in a subsequent file) it would assume that there were no more trees to process and exit.

Correctly handle reading of multiple merger tree files

---

source/merger_trees.construct.build.masses.read.F90
source/merger_trees.construct.build.masses.read.XML.F90
source/merger_trees.construct.build.masses.replicate.F90

* Make tree weights optional when replicating tree masses;
* Set minimum and maximum mass interval for trees when multiple trees have the same mass;
* Check `treeRootMass` and `treeWeight` arrays have the same size.

Various fixes related to reading tree masses from file

---

source/utility.input_parameters.F90

For counting parameters parameters are read as text (even if they are numerical). If evaluated this would cause text parameter requirements to be asserted which would fail.

Do not evaluate parameters when counting them

---

.github/workflows/cicd.yml
source/nodes.operators.physics.satellite.heating.tidal.F90
source/nodes.operators.physics.satellite.mass_loss.tidal.F90
source/objects.kepler_orbits.F90
source/objects.nodes.components.satellite.orbiting.F90
testSuite/regressions/preInfallEvolutionNotOnMainBranch.xml

* Do not apply pre-infall physics on the main branch;
* Allow multiple satellite components on a branch if their orbits are equal;
* Add a test model for pre-infall physics.

Fix pre infall evolution

---

.github/workflows/cicd.yml
Makefile

There is no static `libgit2` available, so the binaries will fail on any system that does not have `libgit2` installed

Do not use `libgit2` for MacOS static builds

---

source/output.analyses.stellar_vs_halo_mass_relation.COSMOS_Leauthaud2012.F90

When using a subset of bins to compute the likelihood, the inactive bins must be excluded from the calculation of the normalization term in the likelihood.

Correctly calculate the likelihood when including the normalization term with a subset of bins

---

source/error.F90

Doing so caused segfaults because the linked list of warning messages would then be assumed to be initialized, even though it wasn't.

Do not record that warnings have been found if the verbosity level is sufficient that they will be reported immediately

---

source/models.likelihoods.independent_likelihoods.F90

When combining multiple, independent model likelihoods, if no `parameterMap` is specified, assume a default map that contains every active parameter.

Allow a default `parameterMap` that includes all parameters

---

.github/actions/buildMacOS/action.yml
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm

If no matching parameter can be found in a class when attempting to build an auto-descriptor, we now provide a guess of which parameter was intended by comparing the given name to the available names using the Levenshtein distance.

Provide a guess for a parameter name when no matching parameter is found in auto-descriptor

---

.github/workflows/cicd.yml
perl/Galacticus/Build/SourceTree/Process/FunctionClass.pm
source/merger_trees.build.controller.mass_time_window.F90
source/merger_trees.construct.builder.constrained.F90
source/nodes.property_extractor.multi.F90
source/tasks.evolve_forests.F90
testSuite/parameters/constrainedMilkyWay.xml

Allows building of constrained merger trees in a sequential manner. Any number of (`mergerTreeBuilder`,`mergerTreeFilter`) pairs can be specified. Building is performed starting with the first `mergerTreeBuilder` (which may be given a `mergerTreeController` to limit the build to only that region of interest to the corresponding `mergerTreeFilter`). If the tree does not pass the corresponding `mergerTreeFilter` it is restored to the state at the start of this step in the sequence. Once the tree passes the corresponding `mergerTreeFilter` building continues with the next (`mergerTreeBuilder`,`mergerTreeFilter`) pair in the sequence. This allows constrain
ts to be applied sequentially.
Includes a test case which builds a Milky Way merger tree with both LMC and GSE mergers.

Add a constrained merger tree builder

---

perl/Galacticus/Build/SourceTree.pm
perl/Galacticus/Build/SourceTree/Process/EventHooksStatic.pm
scripts/build/useDependencies.pl
source/events.hooks.F90
source/instruments.filters.F90
source/merger_trees.evolve.timesteps.history.F90
source/output.HDF5.open.F90
source/output.build.F90
source/output.version.F90
source/utility.OpenMP.F90
source/utility.memory_reporting.F90

Replaces the use of `include` directives in some instances - this allows such build-time-determinable function calls to be handled by the source code preprocessor instead of via include files.
Remaining use of `include` directives is expected to be factored out via other means (e.g. moving physics from `nodeComponent`s to `nodeOperator`s).

Add an `eventHookStatic` directive

---

source/posterior_sampling.state.samples.prior_grid.F90
source/utility.multi_counter.F90

Was previously multiplying the grid size by the number of parameters, instead of raising to that power.

Fix sample grid state size for the `posteriorSamplesPriorGrid` class

---

perl/Galacticus/Build/Components/Implementations/ODESolver.pm

Previously these were allocated to a size equal to the number of *evolvable* meta-properties. But, as they are indexed by meta-property index, they must have a size equal to the *total* number of meta-properties, including those that are not evolvable.

Ensure that the arrays used to store serialization offsets for meta-properties are of sufficient length

---

source/output.analyses.correlation_function.F90
source/output.analyses.mean_function_1d.F90
source/output.analyses.scatter_function_1d.F90
source/output.analyses.stellar_vs_halo_mass_relation.COSMOS_Leauthaud2012.F90
source/output.analyses.volume_function_1d.F90

Compute likelihood for the scatter in the stellar mass-halo mass relation using only active bins. Specifically, removes inactive bins from the data vector and covariance matrix before evaluating the likelihood.
In the normalization of a multivariate Gaussian, there is a term $\mathrm{det}(\mathbf{\Sigma})^{-1/2}$. Previously, when evaluating log-likelihoods, this was included as $-(1/2) \mathrm{det}(\mathbf{\Sigma})$ instead of $-(1/2) \log \mathrm{det}(\mathbf{\Sigma})$. This is now corrected.

Fix issues in the normalization of log-likelihoods in `outputAnalysis` classes

---

source/satellites.merging.virial_orbits.Wetzel2010.F90

The wrong variable (`radiusHost`) was used in a function call resulting in use of an uninitialized value (`radiusHostSelf`) later in the calculation.

Correct variable used in function call in the `virialOrbitWetzel2010` class

---

source/flock.c
source/utility.files.F90

Report a warning if a lock can not be acquired, but continue attempts to acquire.

Add a timeout for file lock requests

---

source/satellites.tidal_heating.rate.Gnedin1999.F90

A condition was evaluated but never used - remove it.

Remove an unused condition

---

.github/workflows/cicd.yml
scripts/build/sourceDigests.pl
source/kinematic_distributions.collisionless.tabulated.F90
source/mass_distributions.F90
source/mass_distributions.spherical.F90
source/mass_distributions.spherical.cored_NFW.F90
source/mass_distributions.spherical.tabulated.F90
source/tests.mass_distributions.tabulated.F90
source/utility.multi_counter.F90

- Works for any parametric, spherically-symmetric, collisionless mass distribution
- Class must specify methods:
- `density()` - gives $\rho(r)$ (optionally also `densityGradientRadial()` - easy to derive);
- `parameters()` - returns $\hat{\rho}$, $\hat{r}$, $\mathbf{p}$ (density normalization, radius normalization, other parameters);
- `factoryTabulation()` - returns an instance of the class with $\hat{\rho}=1$, $\hat{r}=1$, and whatever $\mathbf{p}$ is provided to it - used to perform numerical integrations to build the tables;
- `suffix()` - a suffix for use in tabulation file names (typically an MD5 hash generated automatically from the source code)
- Handles $M(r)$, $\phi(r)$, ℘₁,₂,₃ $(r)$, $\sigma(r)$,  $F(k)$, $E(r)$, $r_\mathrm{ff}(t)$, $\mathrm{d}r_\mathrm{ff}/\mathrm{d}t(t)$;
- …

Add an abstract class which automates tabulation of parametric, spherically-symmetric, collisionless mass distributions

---

scripts/ssps/createEmissionLinesTable.pl
source/nodes.property_extractor.luminosity_emission_line.F90
source/nodes.property_extractor.luminosity_emission_line.Panuzzo2003.F90
source/tests.arrays.F90
source/utility.arrays.F90

Each dataset (e.g. age, metallicity) now stores an index which indicates which dimension of the line table corresponds to that property. This allows Galacticus to programmatically determine the indexing at run time, and manipulate the tables into the required internal order.

Store (and use) indexing information in Cloudy emission line tables

---

source/cooling.cooling_radius.beta_profile.F90

This was being evaluated at the outer radius instead of at zero radius.

The central density of the β-profile was evaluated at the wrong radius in cooling radius calculations

---

source/merger_trees.construct.read.F90
source/objects.kepler_orbits.F90

When constructing subhalo orbits for halos read from merger tree files, if the orbital position vecctor lies prrecisely along the $z$-axis we can not use the normal approach of $\mathbf{r} \times \mathbf{\hat{e}}_\mathrm{z}$ to construct a vector from which to measure the angle $\epsilon$ (angle of motion in the tangential plane). In such cases we now set $\epsilon=\pi/2$ which will be consistent with the result obtained at some slightly later time, as now explained in the `keplerOrbit` class.

Handle edge case for orbital angles read from merger tree files

---

source/dark_matter_profiles.structure.scale.Johnson2021.F90

This allows a different density profile (e.g. NFW) to be provided for these calculations.

Make the `darkMatterProfileScaleRadiusJohnson2021` class get mass distributions directly from the `darkMatterProfileDMO` object

---

source/utility.locks.F90
source/utility.memory_reporting.F90

There's no need for one thread to wait to do memory reporting if another thread is already reporting.

Use a non-blocking lock for coordinating memory reporting

---

source/mass_distributions.cylindrical.F90

Return zero acceleration in such cases.

Catch cases where the velocity dispersion is zero in cylindrical mass distribution Chandrasekhar integrals

---

.github/workflows/cicd.yml

This test requires a lot of memory - by using a dark-matter-only build we can reduce the amount of memory required to stay within available limits.

Build a dark-matter-only executable during CI/CD and use for the PonosV validation test

---

source/dark_matter_halos.spins.distributions.Bett2007.F90
source/dark_matter_halos.spins.distributions.lognormal.F90

* In the `haloSpinDistributionBett2007` class the range of tabulation is now automatically adjusted to ensure that the distribution function is always invertible. Specifically, a large initial maximum spin is tried - if the CDF reaches 1 (to machine precision) before this maximum, the maximum spin is reduced to just before the spin at which the CDF first reaches 1.0, and the table is rebuilt.
* In the `haloSpinDistributionLogNormal` class the median spin was incorrectly used directly in the distribution function - the logarithm of this value should be used instead.

Fix problems in halo spin distribution classes

---

source/merger_trees.construct.builder.Cole2000.F90

Non-well-ordered branches are pruned. This allows these problems to be ignored in cases where they result from unimportant numerical issues.

Allow ignoring of well-ordering errors during tree build

---

.github/workflows/cicd.yml

This should result in lower CPU and memory requirements for these models.

Use the dark matter only executable for dark matter only validation and benchmark models

---

aux/words.dict
source/Galacticus.F90
source/error.F90
source/error.utilities.F90
source/models.likelihoods.F90
source/models.likelihoods.SED_fit.F90
source/models.likelihoods.galaxy_population.F90
source/models.likelihoods.gaussian_regression.F90
source/models.likelihoods.halo_mass_function.F90
source/models.likelihoods.independent_likelihoods.F90
source/models.likelihoods.independent_likelihoods.sequential.F90
source/models.likelihoods.mass_function.F90
source/models.likelihoods.multivariate_normal.F90
source/models.likelihoods.multivariate_normal.stochastic.F90
source/models.likelihoods.posterior_as_prior.F90
source/models.likelihoods.projected_correlation_function.F90
source/models.likelihoods.spin_distribution.F90

This allows writing of the current state as a parameter file when an error is caught.
To enable this, this PR allows arbitrary functions to be called when error signals are caught. Functions can be registered/deregistered and will be called when any fatal signal is caught. The intent is to allow for additional error-reporting functionality.

Add an error handler when evaluating likelihood in the `posteriorSampleLikelihoodGalaxyPopulation` class

---

source/objects.nodes.components.black_hole.standard.F90

A bug was introduced that caused the mass of the central black hole to be reset to the seed mass after any merger, instead of to the mass of the merged black hole.

Set the mass of the central black hole correctly after a merger

---

source/error.utilities.F90

This seems more useful as errors will now cause immediate termination (and notification) of the job. A non-zero wait time can then be set if such is useful for debugging.

Change the MPI wait-on-error time to zero

---

source/kinematic_distributions.undecorator.F90

When computing the velocity dispersion in self-gravitating decorated mass distributions, and the undecorated distribution can be used, we were previously undecorating only the embedding mass distribution, not the target mass distribution. This resulted in a mismatch between target and embedding mass distributions, which caused incorrect results and slow-downs (as analytic solutions for self-gravitating systems could not be used).

Use the correct mass distribution when undecorating kinematics distributions

---

.github/workflows/cicd.yml
Dockerfile

Should allow PR-triggered builds to use the correct repo.

Determine the repo for Docker builds from the `github` context

---

source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.spheroid.standard.F90

When the specific angular momentum was not required in radius solver calculations, the standard disk and spheroid components incorrectly indicated that the component was not active, resulting in no size calculation being performed.

Operate correctly for `galacticStructureRadiusSolvers` that do not require the specific angular momentum of each component

---

source/cooling.specific_angular_momentum.constant_rotation.F90
source/cooling.time_available.Benson_Bower_2010.F90
source/nodes.operators.physics.cooling_energy_radiated.F90

Unphysical hot halo states (e.g., negative mass or radius) result in a `massDistributionZero` being returned. Catch such cases, and assume zero cooling rate in such instances.
Also, for the `coolingSpecificAngularMomentumConstantRotation` class, previously arguments to the `radialDensityMoment` class were unnamed, which resulted in these radii being interpretted as minimum radii. This is now corrected.

Catch unphysical states in the hot halo when using the `coolingTimeAvailableBensonBower2010` class

---

.github/workflows/cicd.yml
source/nodes.property_extractor.galaxy_merger_tree.objects.F90

Caused erroneous warnings due to missing class method descriptors.

Fix a class name conflict

---

source/black_holes.seeds.Vergara2023.F90
source/nodes.operators.physics.nuclear_star_clusters.growth.F90

In the `source/nodes.operators.physics.nuclear_star_clusters.growth.F90` node operator, we were removing angular momentum from the nuclear star cluster instead of adding it from the spheroid.
Additionally, the file `source/black_holes.seeds.Vergara2023.F90` contained unused modules and variables. We also adjusted the stellar mass of the nuclear star cluster before calculating the black hole seed mass, resulting in an incorrect calculation of the initial black hole seed mass.

fix: Correct nuclear star cluster angular momentum rate and black hole seed mass 

---

scripts/build/useDependencies.pl

Now lists the submodule(s) and module(s) in question by name.

Add more information to the error message when submodules are associated with multiple modules

---

source/nodes.operators.physics.cooling_energy_radiated.F90

This _should_ instead happen when a satellite galaxy merges with its central.
The incorrect reset caused the time available for cooling to be reset to zero when a halo became a subhalo.

Radiated energy was incorrectly set to zero when a halo became a subhalo

---

doc/Advanced.tex
doc/Running.tex
source/merger_trees.construct.build.F90
source/merger_trees.construct.fully_specified.F90
source/merger_trees.construct.read.F90
source/merger_trees.construct.state_restore.F90
source/merger_trees.outputter.standard.F90
source/merger_trees.seeds.F90
source/merger_trees.seeds.incremental.F90
source/merger_trees.seeds.random.F90
source/numerical.random_numbers.F90
source/numerical.random_numbers.GSL.F90
source/tasks.evolve_forests.F90
source/tests.mass_accretion_history.Hearin2021_stochastic.F90

The default implementation uses incrementing seeds based on tree index (matching the prior behavior).
A new `mergerTreeSeedsRandom` implementation chooses seeds based on a non-repeating random sequence. This is intended to allow a simple change by 1 in the seed given in the parameter file to generate a completely new set of trees.
Also outputs random number seeds for all trees. This can be useful for recreating a specific tree in a separate run.

Set merger tree seeds using a dedicated class

---

source/merger_trees.filter.tree_index.F90
source/nodes.property_extractor.cooling_energy_radiated.F90
source/nodes.property_extractor.physically_plausible.F90

* Add a `nodePropertyExtractor` that extracts an indicator of whether the node is physically plausible or not;
* Add a `nodePropertyExtractor` to extract the cooling energy radiated in the [Benson & Bower (2010)](http://adsabs.harvard.edu/abs/2010MNRAS.405.1573B) model;
* Add a merger tree filter that selects a tree of the specified index.

Add miscellaneous new classes

---

source/nodes.operators.physics.cooling_energy_radiated.F90

This patch checks that a hot halo component exists before setting the relevant scale for the radiated cooling energy. This situation can occur in models using N-body merger trees in which a halo can be a subhalo at its first appearance, so it never has a hot halo component created in it.

In the `nodeOperatorCoolingEnergyRadiated` class, avoid attempting to set cooling scales in non-existant hot halos

---

source/nodes.property_extractor.mass_stellar_morphology.F90

The disk mass was incorrectly used for the spheroid mass when computing stellar mass spheroid-to-total ratios, resulting in the ratio always being 0.5.

Fix incorrect spheroid mass used in determining morphology

---

perl/Galacticus/Build/SourceTree/Process/ObjectBuilder.pm

In cases where an object has a dependency on an object of the same class (for example in:
```
<cosmologicalMassVariance value="scaled">
<scale value="1.1"/>
<cosmologicalMassVariance value="filteredPower">
<sigma_8 value="0.807"/>
</cosmologicalMassVariance>
</cosmologicalMassVariance>
```
the `cosmologicalMassVarianceScaled` object depends on another object of the `cosmologicalMassVariance` class), if no instance of the dependency is given then an infinite recursion happens as the object build steps up through the parameter hierarchy looking for a member of the class, and finds the original object, triggering an infinite recursion.
This update checks for such recursion and stops with an error message.

Detect recursion in `objectBuilder` directives

---

source/galactic_structure.radius_solver.fixed.F90
source/objects.nodes.components.disk.standard.F90
source/objects.nodes.components.spheroid.standard.F90
testSuite/parameters/starFormationHistoryAdaptive.xml
testSuite/parameters/starFormationHistoryMetallicitySplit.xml

Doing so causes calculation of sizes to be suspended, resulting in sizes being frozen at the value that they had when all components last had positive masses. Removing this allows sizes of components with positive masses to continue to be updated. Those with negative masses are simply ignored during size determination, so have no effect on the results.

Do not mark nodes as physically implausible because of negative disk/spheroid masses

---

source/objects.abundances.F90
testSuite/test-reproducibility.pl

If metallicity is negative (due to ODE solver inaccuracies), do not allow the hydrogen or helium mass fraction to exceed the primordial value.

Prevent hydrogen and helium mass fractions exceeding primordial values for negative metallicities

---

doc/Galacticus.bib
source/structure_formation.transfer_function.Bode2001.F90

Implements the transfer function for WDM from [Vogel & Abazajian (2022)](https://ui.adsabs.harvard.edu/abs/2022arXiv221010753V).
Changes were cherry-picked from the [`dmConstraintPipeline`](https://github.com/galacticusorg/galacticus/tree/dmConstraintPipeline) branch.

Implement the Vogel & Abazajian (2022) transfer function for WDM

---

source/kinematic_distributions.finite-resolution.NFW.F90
source/mass_distributions.spherical.finite_resolution.NFW.F90

This class used the standard `hashedDescriptor()` method to create file name suffixes for tabulated solutions. However, that made the suffix depend on the specific density and radius scales of the mass distribution when the tables are, in fact, computed for the scale-free case. This often resulted in huge numbers of tables being constructed as a new `massDistributionFiniteResolutionNFW` is constructed for each evolution step of each halo.
This fix changes the behavior to use a fixed suffix that depends only on the source code digest.

fix: Avoid creating duplicate tables for the `massDistributionFiniteResolutionNFW` class

---

source/nodes.operators.empirical.UniverseMachine.F90
source/nodes.operators.empirical.central_disk.F90
testSuite/parameters/test-UniverseMachine.xml

The order of evaluations is changed to avoid floating overflows.
This revision also introduces parameters that control the maximum redshift and minimum halo mass for which UniverseMachine fits will be applied. These default to sensible values for which the UniverseMachine was calibrated, avoiding applying the model in regions where the fits may be unreliable.

Make evaluation of UniverseMachine fits more robust

---

source/dark_matter_profiles.structure.concentration.Schneider2015.F90
source/satellites.merging.virial_orbits.Li2020.F90
source/structure_formation.cosmological_density_field.F90

Allows to handle cases where access to the environment is needed.

Pass through `node` to `criticalOverdensity` functions

---

source/mass_distributions.spherical.decorator.F90
source/mass_distributions.spherical.tabulated.F90

Previously, this class had methods only for the `energyPotential` and `energyKinetic` classes. These, correctly, checked whether the undecorated solution could be used, falling through to the decorated class in such cases. However, since no `energy` method was supplied, if the energy was requested, no check was ever performed to see if the undecorated solution could be used. Instead, therefore, the default approach of a numerical solution would be used, resulting in expensive integrations to evaluate potential and kinetic energies. By adding this `energy` method, we can now check if the undecorated solution can be used. In the case of a decorated `massDistributionSphericalTabulated` object (for example), this is much faster as the total energy is tabulated (and so can be returned …

Add an `energy` method to the `massDistributionSphericalDecorator` class

---

source/tests.IO.HDF5.F90
source/utility.IO.HDF5.F90

4GB is the maximum allowed chunk size (see [here](https://support.hdfgroup.org/documentation/hdf5/latest/hdf5_chunking.html#sec_hdf5_chunking_limits)). If this would be exceeded, reduce the chunk size until it is below 4GB. Invludes a test write of a dataset of size greater than 4GB.

 Avoid chunk sizes over 4GB in HDF5 datasets

---

source/tests.IO.HDF5.F90
source/utility.IO.HDF5.F90
source/utility.input_parameters.F90

This allows storing parameter values with lengths exceeding 64KB.

Force the use of dense attribute storage for the `Parameters` group

---

source/utility.input_parameters.F90

Previously, temporary parameter data was written to `/dev/shm/glcTmp*` files. These files were removed once the main file was opened and ready to receive parameters. If an error occurred during parameter reading the temporary file would be left in place, leading to an accumulation of these files.
This revision calls `unlink()` immediately after opening the temporary file. This removes the link to the file in the file system, but keeps it usable. Once the file is closed, the kernel then removes the data associated with the file. If the code crashes, the kernel cleans up any open file handles, also resulting in the data associated with the file being removed. This avoids accumulation of these files.

Avoid persistence of temporary parameter files on error

---

source/dark_matter_profiles_DMO.cusp-NFW.F90
source/kinematic_distributions.collisionless.cusp-NFW.F90
source/kinematic_distributions.collisionless.tabulated.F90
source/mass_distributions.F90
source/mass_distributions.spherical.cusp-NFW.F90

Uses an analytic extrapolation to small radii for the velocity dispersion. This prevents the need to tabulate velocity dispersions to extremely small radii.

Add a kinematics class for the cusp-NFW profile

---

source/objects.stellar_luminosities.F90

Previously the missing filter name (in an error report) was not accounted for.

Correct the maximum filter name length

---

source/objects.nodes.F90

In the `universe` class, make the OpenMP lock object allocatable, and allocate only just before it is initialized. This prevents attempts to finalize an uninitialized lock (which can lead to segfaults and other problems).

Avoid attempts to finalize uninitialized OpenMP locks

---

Makefile

If the `FFTLog` tool can not be downloaded, we inject dummy functions for the top-level functions of the tool, such that the code will still compile, but any attempt to call the tool will issue a warning. One top-level function was missing; we now inject a dummy function for that one as well.

Avoid missing function error if the `FFTLog` tool can not be downloaded

---

doc/Galacticus.bib
source/dark_matter_profiles_DMO.soliton_NFW.F90
source/mass_distributions.spherical.solition_NFW.F90
source/tests.dark_matter_profiles.fuzzy_dark_matter.F90

Added radiusEnclosingDensity function to the Soliton-NFW profile.
Update Soliton-NFW profile with new core-mass relation and fix tests.dark_matter_profiles.fuzzy_dark_matter accordingly.
Updated core-mass relation based on Chan et al. 2022, [https://ui.adsabs.harvard.edu/abs/2022MNRAS.511..943C].

Add a radiusEnclosingDensity function and scatter to core-Mass relation for the Soliton-NFW profile 

---

source/utility.IO.HDF5.F90

The error messages used the older `objectName` attribute (which is not set for files) instead of `objectFile`.

Fix a bug that prevented the file name being reported in HDF5 file open errors

---

parameters/reference/darkMatterHalosStructure.xml
parameters/reference/powerSpectraSuppressed.xml
source/nodes.property_extractor.halo_collapse_epoch.F90
testSuite/validate-concentrationConvergence.py

Commit 0917f7ca17 change the settings of the Diemer & Joyce (2019) concentration model used in reference models to have:
```
<truncateConcentration value="true" />
<includeUpturn         value="false"/>
```
Previously these had not been specified, and so took on the default values - which were the opposites of the above.
This revision reverts this, and now explicitly sets these to:
```
<truncateConcentration value="false"/>
<includeUpturn         value="true" />
```
in the reference model parameter files.
They _are_ inverted for models with suppressed power spectra as the upturn is problematic in such case.

Restore the previous behavior for concentrations in the reference model

---

.github/workflows/cicd.yml
aux/words.dict
parameters/reference/warmDarkMatter.xml
source/nodes.operators.physics.dark_matter_profile.prompt_cusp.F90
source/nodes.operators.physics.dark_matter_profile.prompt_cusp.update.F90
source/tests.prompt_cusps.F90
testSuite/test-concentration-Johnson2021.pl

Also use a definition for halo mass consistent with that used by Delos (2025).
Also add scatter in the cusp amplitude following a model proposed by Sten Delos.

Compute rₛ consistently in cusp-NFW profiles

---

source/nodes.operators.physics.dark_matter_profile.prompt_cusp.F90
source/nodes.property_extractor.prompt_cusps.F90
source/tests.prompt_cusps.F90

This is essentially the limit from the equation in footnote 9 of [Delos (2025)](https://ui.adsabs.harvard.edu/abs/2025arXiv250603240D), and ensures that a solution can be found for the scale radius without violating the $y < 1$ condition.
Also adds extraction of the prompt cusp profile $r_{-2}$ and $\rho_\mathrm{s}$ parameters.

Enforce a limit on r₋₂ in prompt cusp calculations to ensure that a solution can be found

---

source/merger_trees.evolver.standard.F90

When displaying a help message, give more context on where in the parameter file XML the new parameter should be inserted. Use highlighting to illustrate this. Adaptively change the class name used in the help message to reflect the actual class name used in the parameter file.

Improve a help message

---

source/structure_formation.excursion_sets.first_crossing_distribution.Farahi.F90
source/utility.files.F90

Expand file name on initialization. This is necessary to ensure the correct file name is used in locking and existance checks.

Fix excursion set file name expansion
